# Allow the Certificate Decoder command to be invoked from the frontend.
[[permission]]
identifier = "allow-cert-decoder"
description = "Enables the tool_cert_decode command."
commands.allow = ["tool_cert_decode"]
