# Allow the Timezone Converter tool command to be invoked from the frontend.
[[permission]]
identifier = "allow-timezone"
description = "Enables the timezone_process command."
commands.allow = ["timezone_process"]
