// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output string format for an API key.
 */
export type ApiKeyFormat = "raw" | "grouped" | "prefixed";
