// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiKeyCharset } from "./ApiKeyCharset";
import type { ApiKeyFormat } from "./ApiKeyFormat";

/**
 * Input for the API Key Generator tool.
 */
export type ApiKeyInput = { 
/**
 * `u32` so tauri-specta TS export avoids bigint (forbidden for IPC).
 */
count: number, length: number, prefix: string, format: ApiKeyFormat, charset: ApiKeyCharset, };
