// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output from the API Key Generator tool.
 */
export type ApiKeyOutput = { keys: Array<string>, error: string | null, };
