// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Character set used for API key generation.
 */
export type ApiKeyCharset = "alphanumeric" | "alphaOnly" | "hexOnly" | "urlSafe";
