// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output: result string, counts, and optional error message.
 */
export type Base64Output = { result: string, byteCount: number, charCount: number, error: string | null, };
