// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output: the value in every supported base.
 */
export type BaseConverterOutput = { decimal: string, hexadecimal: string, binary: string, binaryGrouped: string, octal: string, base32: string, base36: string, bitLength: number, isNegative: boolean, error: string | null, };
