// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Base64Mode } from "./Base64Mode";

/**
 * Input for the Base64 tool: text to encode or decode, engine choice, and mode.
 */
export type Base64Input = { text: string, urlSafe: boolean, mode: Base64Mode, };
