// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasicAuthMode } from "./BasicAuthMode";

/**
 * Input for the Basic Auth Header tool.
 */
export type BasicAuthInput = { mode: BasicAuthMode, username: string, password: string, header: string, };
