// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BcryptOutput = { 
/**
 * The generated bcrypt hash. Populated in hash mode; empty string in verify mode.
 */
hash: string, 
/**
 * Whether the password matched the hash. `Some(true/false)` in verify mode; `None` in hash mode.
 */
matches: boolean | null, error: string | null, };
