// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BitwiseBase } from "./BitwiseBase";
import type { BitwiseWidth } from "./BitwiseWidth";

/**
 * Input for the bitwise calculator.
 */
export type BitwiseInput = { valueA: string, valueB: string, fromBase: BitwiseBase, bitWidth: BitwiseWidth, shiftAmount: number, };
