// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bit width for binary output (padding and grouping).
 */
export type BitWidth = "auto" | "bit8" | "bit16" | "bit32" | "bit64";
