// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bit width for all operations (determines integer type: u8, u16, u32, u64).
 */
export type BitwiseWidth = "bit8" | "bit16" | "bit32" | "bit64";
