// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for the Text Case Converter tool.
 */
export type CaseInput = { text: string, };
