// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DnField } from "./DnField";

export type CertInfo = { subject: string, subjectFields: Array<DnField>, issuer: string, issuerFields: Array<DnField>, serialNumber: string, notBefore: string, notAfter: string, isExpired: boolean, expiryWarning: boolean, daysUntilExpiry: bigint, signatureAlgorithm: string, publicKeyAlgorithm: string, publicKeySize: number | null, sans: Array<string>, isCa: boolean, keyUsages: Array<string>, extendedKeyUsages: Array<string>, fingerprintSha256: string, version: number, };
