// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CertInfo } from "./CertInfo";

export type CertDecodeOutput = { certificates: Array<CertInfo>, error: string | null, };
