// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Type of change between left and right.
 */
export type ChangeType = "added" | "removed" | "changed" | "typeChanged";
