// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input — the raw permission string (octal "755", symbolic "rwxr-xr-x", etc.)
 */
export type ChmodInput = { value: string, };
