// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubnetSplit } from "./SubnetSplit";

export type CidrOutput = { networkAddress: string, broadcastAddress: string | null, subnetMask: string, wildcardMask: string, firstHost: string | null, lastHost: string | null, totalHosts: bigint, usableHosts: bigint, prefixLength: number, ipVersion: number, ipClass: string | null, isPrivate: boolean, isLoopback: boolean, binaryMask: string, 
/**
 * Number of host bits.
 */
hostBits: number, 
/**
 * Number of wildcard bits.
 */
wildcardBits: number, 
/**
 * IPv6 scope classification.
 */
ipv6Scope: string | null, 
/**
 * Human-readable note for special prefix lengths.
 */
specialNote: string | null, 
/**
 * Subnet split preview.
 */
subnetSplit: SubnetSplit | null, error: string | null, };
