// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output — all four colour formats plus an optional CSS name.
 */
export type ColorOutput = { hex: string, rgb: string, hsl: string, hsb: string, name: string | null, error: string | null, };
