// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ColorContrastOutput = { 
/**
 * Contrast ratio, e.g. 4.54.
 */
ratio: number, 
/**
 * Human-readable ratio string, e.g. "4.54:1".
 */
ratioDisplay: string, 
/**
 * WCAG AA — normal text (≥4.5:1).
 */
aaNormal: boolean, 
/**
 * WCAG AA — large text / UI components (≥3.0:1).
 */
aaLarge: boolean, 
/**
 * WCAG AAA — normal text (≥7.0:1).
 */
aaaNormal: boolean, 
/**
 * WCAG AAA — large text (≥4.5:1).
 */
aaaLarge: boolean, 
/**
 * Normalised foreground hex (always `#RRGGBB` uppercase).
 */
foregroundHex: string, 
/**
 * Normalised background hex (always `#RRGGBB` uppercase).
 */
backgroundHex: string, 
/**
 * Set when either colour cannot be parsed.
 */
error: string | null, };
