// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CronInput = { expression: string, 
/**
 * How many upcoming run times to return (default 5, max 10).
 */
count: number | null, };
