// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parsed CSV output ready for table rendering.
 */
export type CsvPreviewOutput = { 
/**
 * Column headers (empty when `has_headers` is false).
 */
headers: Array<string>, 
/**
 * Data rows (up to `max_rows`).
 */
rows: Array<Array<string>>, 
/**
 * Total rows in the file (may exceed `rows.len()` when truncated).
 */
totalRows: number, truncated: boolean, error: string | null, };
