// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for the CSV Previewer.
 */
export type CsvPreviewInput = { text: string, hasHeaders: boolean, delimiter: string, 
/**
 * Maximum rows to return (default 1000).
 */
maxRows: number | null, };
