// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeType } from "./ChangeType";

/**
 * A single diff change at a path.
 */
export type DiffChange = { 
/**
 * Dot-notation path, e.g. "user.name", "items[0].price".
 */
path: string, changeType: ChangeType, 
/**
 * JSON-serialised value on the left (None for Added).
 */
leftValue: string | null, 
/**
 * JSON-serialised value on the right (None for Removed).
 */
rightValue: string | null, };
