// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EnvEntry = { key: string, value: string, rawValue: string, lineNumber: number, isEmptyValue: boolean, isComment: boolean, isQuoted: boolean, 
/**
 * For .ini files: the section this key belongs to. None for .env/.properties.
 */
section: string | null, 
/**
 * True if this entry is a section header.
 */
isSection: boolean, };
