// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EnvIssue = { lineNumber: number, kind: string, severity: string, message: string, key: string | null, };
