// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvFileFormat } from "./EnvFileFormat";

export type EnvParseInput = { content: string, format: EnvFileFormat, 
/**
 * If true, mask values that look like secrets.
 */
maskValues: boolean, };
