// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Target format: JSON, Regex, HTML, SQL, Shell, CSV.
 */
export type EscapeTarget = "json" | "regex" | "html" | "sql" | "shell" | "csv";
