// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One field definition in the schema.
 */
export type FakeField = { 
/**
 * The key name in the output JSON object.
 */
name: string, 
/**
 * The data type identifier (e.g. "email", "city", "uuid").
 */
fieldType: string, 
/**
 * Optional parameters for parameterised types.
 */
params: Record<string, unknown> | null, };
