// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FakeField } from "./FakeField";

export type FakeDataInput = { fields: Array<FakeField>, 
/**
 * Number of records to generate (capped at 500).
 */
count: number, };
