// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for the Find & Replace tool.
 */
export type FindReplaceInput = { text: string, find: string, replace: string, caseSensitive: boolean, wholeWord: boolean, regexMode: boolean, replaceAll: boolean, };
