// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output: result string, total matches found, number replaced, match ranges, optional error.
 * match_ranges: [start_byte, end_byte] of each match in the ORIGINAL text.
 * Empty when find is empty, no matches, or on error.
 */
export type FindReplaceOutput = { result: string, matchCount: number, replacedCount: number, matchRanges: Array<[number, number]>, error: string | null, };
