// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HashOutputFormat } from "./HashOutputFormat";

export type HashInput = { 
/**
 * Text to hash (UTF-8).
 */
text: string, 
/**
 * If true, empty/whitespace-only input is hashed; otherwise all results are empty.
 */
hashEmpty: boolean, 
/**
 * Output encoding for all algorithms.
 */
outputFormat: HashOutputFormat, 
/**
 * If true and format is Hex, return uppercase hex. Ignored for Base64/Base64url.
 */
uppercase: boolean, 
/**
 * Optional HMAC secret key. When non-empty, all algorithms run as HMAC-<algo>.
 */
hmacKey: string, };
