// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output for the Hex converter.
 */
export type HexOutput = { result: string, byteCount: number, error: string | null, };
