// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Separator style when encoding bytes to hex.
 */
export type HexSeparator = "none" | "space" | "colon" | "dash";
