// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output: result string, count of entities encoded/decoded, and optional error.
 */
export type HtmlEntityOutput = { result: string, entitiesFound: number, error: string | null, };
