// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HtmlFormatInput = { 
/**
 * Raw HTML to format.
 */
code: string, 
/**
 * Spaces per indent level, or `0` for tabs.
 */
indentSize: number, 
/**
 * Prefer each attribute on its own line when a tag has multiple attributes.
 */
wrapAttributes: boolean, 
/**
 * Soft wrap width (used by the formatter layout engine; strongest effect with wrap attributes on).
 */
printWidth: number, };
