// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageConvertOutput = { data: string, format: string, width: number, height: number, sizeBytes: number, error: string | null, };
