// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Indentation style for Pretty mode.
 */
export type IndentStyle = "spaces2" | "spaces4" | "tab";
