// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnnotatedLine } from "./JsonDiffAnnotatedLine";
import type { DiffChange } from "./DiffChange";

/**
 * Output from the JSON diff tool.
 */
export type JsonDiffOutput = { isIdentical: boolean, leftValid: boolean, rightValid: boolean, changes: Array<DiffChange>, 
/**
 * `u32` for tauri-specta export (no bigint in TS bindings).
 */
addedCount: number, removedCount: number, changedCount: number, unchangedCount: number, leftAnnotated: Array<AnnotatedLine>, rightAnnotated: Array<AnnotatedLine>, error: string | null, };
