// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SchemaDraft } from "./SchemaDraft";

/**
 * Input for JSON Schema validation.
 */
export type JsonSchemaValidateInput = { 
/**
 * The JSON document to validate (raw string).
 */
document: string, 
/**
 * The JSON Schema to validate against (raw string).
 */
schema: string, 
/**
 * Which schema draft to use (defaults to draft7).
 */
draft: SchemaDraft, };
