// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Format mode for JSON output.
 */
export type JsonFormatMode = "pretty" | "minify" | "compact";
