// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonPathMatch } from "./JsonPathMatch";

/**
 * Output from the JSONPath tool.
 */
export type JsonPathOutput = { isValidJson: boolean, isValidQuery: boolean, matches: Array<JsonPathMatch>, matchCount: number, error: string | null, 
/**
 * Pretty-printed full JSON document (no inline annotations yet).
 */
annotatedDocument: string | null, };
