// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversionTarget } from "./ConversionTarget";

export type JsonConvertOutput = { result: string, isValidJson: boolean, target: ConversionTarget, error: string | null, 
/**
 * Non-fatal warnings about lossy transforms, etc.
 */
warning: string | null, lineCount: number, charCount: number, };
