// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for the JSON validator.
 */
export type JsonValidateInput = { 
/**
 * Raw JSON string to validate.
 */
value: string, };
