// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JsonToCsvOutput = { 
/**
 * CSV text output.
 */
result: string, 
/**
 * Number of data rows (excluding header).
 */
rowCount: number, 
/**
 * Number of columns.
 */
columnCount: number, 
/**
 * Non-fatal warning (e.g. "Nested objects serialised as JSON").
 */
warning: string | null, 
/**
 * Error message if conversion failed.
 */
error: string | null, };
