// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndentStyle } from "./IndentStyle";
import type { JsonFormatMode } from "./JsonFormatMode";

/**
 * Input for the JSON formatter.
 */
export type JsonFormatInput = { 
/**
 * Raw JSON string to format.
 */
value: string, 
/**
 * Output format mode.
 */
mode: JsonFormatMode, 
/**
 * Indentation style in Pretty mode.
 */
indent: IndentStyle, 
/**
 * If true, sort object keys alphabetically.
 */
sortKeys: boolean, };
