// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineAnnotation } from "./JsonDiffLineAnnotation";

/**
 * A single line in the annotated diff output.
 */
export type AnnotatedLine = { lineNumber: number, 
/**
 * Line text without prefix.
 */
content: string, annotation: LineAnnotation, };
