// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Annotation for a single line in the diff view.
 */
export type LineAnnotation = "unchanged" | "added" | "removed" | "changed";
