// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output of JWT build.
 */
export type JwtBuildOutput = { token: string, headerJson: string, payloadJson: string, headerB64: string, payloadB64: string, signatureB64: string, algorithm: string, expiresAt: string | null, issuedAt: string | null, error: string | null, };
