// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output of JWT decode.
 */
export type JwtDecodeOutput = { 
/**
 * Base64url-decoded header JSON.
 */
headerRaw: string, 
/**
 * Base64url-decoded payload JSON.
 */
payloadRaw: string, 
/**
 * Signature bytes as hex.
 */
signatureRaw: string, algorithm: string, tokenType: string, keyId: string | null, subject: string | null, issuer: string | null, audience: string | null, issuedAt: bigint | null, expiresAt: bigint | null, notBefore: string | null, jwtId: string | null, issuedAtHuman: string | null, expiresAtHuman: string | null, isExpired: boolean | null, timeUntilExpiry: string | null, 
/**
 * exp - iat when both present.
 */
lifetimeSeconds: bigint | null, 
/**
 * Human-readable lifetime, e.g. "28 days", "2 hours".
 */
lifetimeHuman: string | null, 
/**
 * (now - iat) / (exp - iat) * 100, clamped 0.0–100.0.
 */
consumedPercent: number | null, 
/**
 * true if current time >= nbf; None if nbf not in token.
 */
nbfActive: boolean | null, 
/**
 * Full payload claims as pretty JSON.
 */
allClaims: string, signatureValid: boolean | null, signatureNote: string, partCount: number, isWellFormed: boolean, error: string | null, };
