// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoremOutputType } from "./LoremOutputType";

/**
 * Input for the Lorem Ipsum generator.
 */
export type LoremIpsumInput = { outputType: LoremOutputType, count: number, startWithClassic: boolean, };
