// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for the MD5 Hash tool.
 */
export type Md5Input = { 
/**
 * Text to hash (UTF-8). Empty string is valid and returns the MD5 of empty input.
 */
text: string, 
/**
 * If true, return hash in uppercase hex (A–F); otherwise lowercase (a–f).
 */
uppercase: boolean, };
