// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output of MD5 hashing.
 */
export type Md5Output = { 
/**
 * 32-character hex hash.
 */
hash: string, 
/**
 * Always 32 for MD5.
 */
length: number, 
/**
 * Set when hashing fails (e.g. invalid UTF-8); normally None.
 */
error: string | null, };
