// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input base for the number string.
 */
export type NumberBase = "decimal" | "hexadecimal" | "binary" | "octal" | "base32" | "base36";
