// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Word separator style.
 */
export type PassphraseSeparator = "Hyphen" | "Space" | "Dot" | "Underscore" | "None";
