// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PassphraseSeparator } from "./PassphraseSeparator";

/**
 * Input for the Passphrase Generator tool.
 */
export type PassphraseInput = { 
/**
 * Number of words per passphrase. Clamped to 3–12.
 */
wordCount: number, 
/**
 * Number of passphrases to generate. Clamped to 1–20.
 */
count: number, separator: PassphraseSeparator, 
/**
 * Capitalise the first letter of each word.
 */
capitalize: boolean, 
/**
 * Append a random digit (0–9) at the end.
 */
includeNumber: boolean, 
/**
 * Append a random symbol from `!@#$%&*?` at the end.
 */
includeSymbol: boolean, };
