// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output from the Passphrase Generator tool.
 */
export type PassphraseOutput = { passphrases: Array<string>, 
/**
 * Shannon entropy in bits (log2(wordlist) * words, + extras).
 */
entropyBits: number, wordCount: number, wordlistSize: number, error: string | null, };
