// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QrCodeOutput = { 
/**
 * Complete SVG string, ready to embed or display.
 */
svg: string, 
/**
 * Side length of the QR code in modules (excluding quiet zone).
 */
size: number, 
/**
 * QR version number (1-40).
 */
qrVersion: number, 
/**
 * Approximate max byte capacity for current version + EC level.
 */
maxBytes: number, 
/**
 * Input length in UTF-8 bytes.
 */
inputBytes: number, error: string | null, };
