// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QrEcLevel } from "./QrEcLevel";

export type QrCodeInput = { text: string, ecLevel: QrEcLevel, 
/**
 * Size of each module in the SVG.
 */
moduleSize: number, 
/**
 * Foreground colour as CSS hex string.
 */
fgColor: string, 
/**
 * Background colour as CSS hex string.
 */
bgColor: string, 
/**
 * Quiet zone size in modules.
 */
margin: number, };
