// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RsaKeygenOutput = { publicKey: string, privateKey: string, algorithm: string, error: string | null, };
