// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which JSON Schema draft to use for validation.
 */
export type SchemaDraft = "draft7" | "2019-09" | "2020-12";
