// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the verification secret is encoded.
 */
export type SecretEncoding = "utf8" | "base64" | "hex";
