// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for the Semver tool.
 */
export type SemverInput = { 
/**
 * Version string (optional leading `v` is stripped).
 */
version: string, 
/**
 * Optional second version to compare (`Ordering` in `compare_result`).
 */
compareWith: string | null, 
/**
 * Optional requirement string (e.g. `^1.0.0`, `>=1.2.3 <2.0.0`).
 */
range: string | null, };
