// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for the SHA-256 Hash tool.
 */
export type Sha256Input = { 
/**
 * Text to hash (UTF-8).
 */
text: string, 
/**
 * If true, return hash in uppercase hex (A–F); otherwise lowercase (a–f).
 */
uppercase: boolean, 
/**
 * If true, empty or whitespace-only input is hashed; otherwise empty output is returned.
 */
hashEmpty: boolean, };
