// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output of SHA-512 hashing.
 */
export type Sha512Output = { 
/**
 * 128-character hex hash, or empty when input is empty and hash_empty is false.
 */
hash: string, 
/**
 * 128 when a hash is returned, 0 when empty.
 */
length: number, 
/**
 * Set when hashing fails; normally None.
 */
error: string | null, };
