// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SqlIndentStyle } from "./SqlIndentStyle";
import type { SqlKeywordCase } from "./SqlKeywordCase";

export type SqlFormatInput = { 
/**
 * Raw SQL string to format.
 */
value: string, 
/**
 * Indentation style.
 */
indent: SqlIndentStyle, 
/**
 * Keyword casing style.
 */
keywordCase: SqlKeywordCase, };
