// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output: result string, number of replacements, optional error.
 */
export type StringEscaperOutput = { result: string, changes: number, error: string | null, };
