// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EscapeMode } from "./EscapeMode";
import type { EscapeTarget } from "./EscapeTarget";

/**
 * Input for the String Escaper tool.
 */
export type StringEscaperInput = { text: string, mode: EscapeMode, target: EscapeTarget, };
