// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InlineSpan } from "./TextDiffSpan";
import type { LineAnnotation } from "./TextDiffLineAnnotation";

export type AnnotatedLine = { lineNumber: number, content: string, annotation: LineAnnotation, 
/**
 * Inline spans for word/char granularity on changed lines.
 * Empty for unchanged lines or when granularity is Line.
 */
spans: Array<InlineSpan>, 
/**
 * true when char granularity fell back to full-line highlight.
 */
fellBack: boolean, };
