// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Conversion direction or "current time".
 */
export type TimestampMode = "toHuman" | "toUnix" | "now";
