// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimestampMode } from "./TimestampMode";
import type { TimestampUnit } from "./TimestampUnit";

/**
 * Input for the timestamp converter.
 */
export type TimestampInput = { 
/**
 * The timestamp or date string to convert (ignored when mode is Now).
 */
value: string, mode: TimestampMode, 
/**
 * Only used when mode is ToHuman: treat value as seconds or milliseconds.
 */
unit: TimestampUnit, };
