// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output of the timezone conversion.
 */
export type TimezoneOutput = { 
/**
 * Converted datetime, e.g. "2024-03-04 07:00:00".
 */
result: string, 
/**
 * ISO 8601 with offset, e.g. "2024-03-04T07:00:00-05:00".
 */
resultIso: string, fromOffset: string, toOffset: string, fromAbbr: string, toAbbr: string, fromDst: boolean, toDst: boolean, 
/**
 * e.g. "+5 hours", "-5 hours", "+5:30 hours", "0 hours (same zone)".
 */
difference: string, error: string | null, };
