// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output: all formats for the resolved instant.
 */
export type TimestampOutput = { unixSeconds: bigint, unixMilliseconds: bigint, 
/**
 * e.g. 2024-03-04T12:00:00Z
 */
iso8601: string, 
/**
 * e.g. Mon, 04 Mar 2024 12:00:00 +0000
 */
rfc2822: string, 
/**
 * e.g. 2024-03-04 12:00:00 UTC
 */
utcHuman: string, 
/**
 * e.g. 2024-03-04
 */
dateOnly: string, 
/**
 * e.g. 12:00:00
 */
timeOnly: string, 
/**
 * e.g. Monday
 */
dayOfWeek: string, 
/**
 * e.g. "2 days ago", "in 3 hours", "just now"
 */
relative: string, isFuture: boolean, error: string | null, };
