// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UaParseOutput = { 
/**
 * Browser name, e.g. "Chrome", "Firefox", "Safari".
 */
browserName: string | null, 
/**
 * Browser version string, e.g. "120.0.0.0".
 */
browserVersion: string | null, 
/**
 * Operating system name, e.g. "Mac OSX", "Windows", "iOS".
 */
os: string | null, 
/**
 * OS version string if available.
 */
osVersion: string | null, 
/**
 * High-level device classification: "Desktop", "Mobile", "Tablet", "Bot", "Other", "Unknown".
 */
deviceType: string, 
/**
 * Rendering engine: "Blink", "Gecko", "WebKit", "Trident", "EdgeHTML", or "Presto".
 */
engine: string | null, 
/**
 * True when the UA belongs to a crawler, bot, or spider.
 */
isBot: boolean, 
/**
 * Hardware vendor if detectable (e.g. "Apple", "Samsung").
 */
vendor: string | null, 
/**
 * Raw woothee category string for reference ("pc", "smartphone", "crawler", etc.).
 */
category: string, error: string | null, };
