// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output from the ULID Generator tool.
 */
export type UlidOutput = { 
/**
 * Generated ULIDs as 26-character Base32 strings.
 */
ulids: Array<string>, 
/**
 * Optional error message when generation fails (e.g. invalid count).
 */
error: string | null, };
