// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One inspected character row.
 */
export type UnicodeChar = { char: string, codepoint: number, hex: string, name: string, block: string, category: string, utf8Bytes: Array<number>, utf8Hex: string, };
