// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnitCategory } from "./UnitCategory";

export type UnitConverterInput = { value: number, 
/**
 * Short unit key, e.g. "km", "mb", "fahrenheit". See unit tables below.
 */
fromUnit: string, category: UnitCategory, };
