// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UrlEncodeMode } from "./UrlEncodeMode";
import type { UrlEncodeType } from "./UrlEncodeType";

/**
 * Input for the URL encode/decode tool.
 */
export type UrlEncodeInput = { text: string, mode: UrlEncodeMode, encodeType: UrlEncodeType, };
