// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryParam } from "./QueryParam";

/**
 * Output from the URL parser.
 */
export type UrlParseOutput = { scheme: string | null, username: string | null, password: string | null, host: string | null, port: number | null, path: string | null, 
/**
 * Raw query string (as in the URL, not decoded).
 */
query: string | null, 
/**
 * Parsed key/value pairs (decoded).
 */
params: Array<QueryParam>, fragment: string | null, 
/**
 * scheme + host + port when origin is a tuple (opaque origins yield None).
 */
origin: string | null, error: string | null, };
