// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UuidVersion } from "./UuidVersion";

/**
 * Input for the UUID Generator tool.
 */
export type UuidInput = { 
/**
 * UUID version to generate (V4 random, V7 time-ordered).
 */
version: UuidVersion, 
/**
 * Number of UUIDs to generate (1–100).
 */
count: number, 
/**
 * If true, return UUIDs in uppercase; otherwise lowercase.
 */
uppercase: boolean, };
