// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single validation issue (one schema violation).
 */
export type ValidationIssue = { 
/**
 * JSON Pointer path to the failing instance node (e.g. "/user/age").
 */
instancePath: string, 
/**
 * Human-readable error message.
 */
message: string, 
/**
 * JSON Pointer path into the schema that produced the error.
 */
schemaPath: string, };
