// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type XmlFormatOutput = { 
/**
 * Formatted XML string.
 */
result: string, 
/**
 * Number of lines in formatted output.
 */
lineCount: number, 
/**
 * Character count of formatted output.
 */
charCount: number, 
/**
 * Error message if parsing/formatting failed.
 */
error: string | null, };
