// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type XmlFormatInput = { 
/**
 * Raw XML text to format.
 */
value: string, 
/**
 * Indentation size in spaces (2 or 4). Defaults to 2.
 */
indentSize: number, };
