// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type YamlToJsonOutput = { result: string, isValidYaml: boolean, error: string | null, errorLine: number | null, errorColumn: number | null, lineCount: number, charCount: number, };
