// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Base32Mode } from "./Base32Mode";
import type { Base32Variant } from "./Base32Variant";

export type Base32Input = { text: string, variant: Base32Variant, mode: Base32Mode, };
