// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BitWidth } from "./BitWidth";
import type { NumberBase } from "./NumberBase";

/**
 * Input for the base converter.
 */
export type BaseConverterInput = { value: string, fromBase: NumberBase, bitWidth: BitWidth, uppercaseHex: boolean, };
