// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Combined output.
 */
export type BaseNOutput = { result: string, error: string | null, };
