// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Base58Mode } from "./Base58Mode";

export type Base58Input = { text: string, mode: Base58Mode, };
