// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shared mode — applies to both encodings.
 */
export type BaseNMode = "encode" | "decode";
