// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Base32Variant } from "./Base32Variant";
import type { BaseNEncoding } from "./BaseNEncoding";
import type { BaseNMode } from "./BaseNMode";

/**
 * Combined input for the Base32 / Base58 tool.
 */
export type BaseNInput = { text: string, encoding: BaseNEncoding, mode: BaseNMode, 
/**
 * Only used when `encoding` is `Base32`.
 */
base32Variant: Base32Variant, };
