// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output: always all fields present; unused strings are empty on error or opposite mode.
 */
export type BasicAuthOutput = { encoded: string, decodedUsername: string, decodedPassword: string, rawBase64: string, error: string | null, };
