// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether to encode credentials to a header or decode an existing header.
 */
export type BasicAuthMode = "encode" | "decode";
