// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BcryptInput = { 
/**
 * `"hash"` or `"verify"`.
 */
mode: string, password: string, 
/**
 * Cost factor (4–31). Used only in hash mode. UI default is 12.
 */
cost: number, 
/**
 * Existing bcrypt hash to verify against. Used only in verify mode.
 */
hash: string, };
