// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BitwiseResult } from "./BitwiseResult";

/**
 * Output: two-operand ops, single-operand ops, and bit analysis of A.
 */
export type BitwiseOutput = { and: BitwiseResult | null, or: BitwiseResult | null, xor: BitwiseResult | null, nand: BitwiseResult | null, nor: BitwiseResult | null, notA: BitwiseResult | null, shiftLeft: BitwiseResult | null, shiftRight: BitwiseResult | null, rotateLeft: BitwiseResult | null, rotateRight: BitwiseResult | null, bitCountA: number | null, leadingZerosA: number | null, trailingZerosA: number | null, isPowerOfTwoA: boolean | null, error: string | null, };
