// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One operation result in multiple bases.
 */
export type BitwiseResult = { decimal: string, hexadecimal: string, binary: string, binaryGrouped: string, octal: string, };
