// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input base for parsing value A and B.
 */
export type BitwiseBase = "decimal" | "hexadecimal" | "binary" | "octal";
