// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output for the Text Case Converter tool: all case variants at once.
 */
export type CaseOutput = { camelCase: string, pascalCase: string, snakeCase: string, screamingCase: string, kebabCase: string, titleCase: string, upperCase: string, lowerCase: string, dotCase: string, pathCase: string, wordCount: number, error: string | null, };
