// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionClass } from "./PermissionClass";

/**
 * Full output.
 */
export type ChmodOutput = { octal: string, symbolic: string, decimal: number, chmodCommand: string, owner: PermissionClass, group: PermissionClass, others: PermissionClass, setuid: boolean, setgid: boolean, sticky: boolean, error: string | null, };
