// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ColorContrastInput = { 
/**
 * Foreground colour — 3 or 6-digit hex, with or without `#`.
 */
foreground: string, 
/**
 * Background colour — 3 or 6-digit hex, with or without `#`.
 */
background: string, };
