// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output from the Config Converter tool.
 */
export type ConfigConvertOutput = { result: string, isValidInput: boolean, error: string | null, 
/**
 * Line number of parse error (1-based), if available.
 */
errorLine: number | null, 
/**
 * Column number of parse error (1-based), if available.
 */
errorColumn: number | null, lineCount: number, charCount: number, };
