// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigFormat } from "./ConfigFormat";

/**
 * Input for the Config Converter tool.
 */
export type ConfigConvertInput = { value: string, from: ConfigFormat, to: ConfigFormat, 
/**
 * JSON/YAML output indent (2 or 4). Ignored when output is TOML.
 */
indent: number, 
/**
 * Sort keys alphabetically. Only applies to JSON output.
 */
sortKeys: boolean, };
