// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CronOutput = { isValid: boolean, description: string, 
/**
 * Next N run times as ISO 8601 strings (UTC).
 */
nextRuns: Array<string>, error: string | null, };
