// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CsvOutputFormat } from "./CsvOutputFormat";

export type CsvToJsonInput = { 
/**
 * Raw CSV text.
 */
value: string, 
/**
 * Treat first row as header names.
 */
hasHeaders: boolean, 
/**
 * Single-character delimiter: ",", "\t", "|", ";" etc.
 */
delimiter: string, 
/**
 * Output layout.
 */
outputFormat: CsvOutputFormat, };
