// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CsvToJsonOutput = { 
/**
 * Pretty-printed JSON string.
 */
result: string, 
/**
 * Number of data rows (excluding header when has_headers == true).
 */
rowCount: number, 
/**
 * Number of columns detected (max across rows / headers).
 */
columnCount: number, 
/**
 * Error message if parsing failed.
 */
error: string | null, };
