// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DnsRecord } from "./DnsRecord";

export type DnsLookupOutput = { domain: string, recordType: string, records: Array<DnsRecord>, error: string | null, };
