// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DnsRecord = { value: string, ttl: number, 
/**
 * MX priority only — None for all other record types
 */
priority: number | null, };
