// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvEntry } from "./EnvEntry";
import type { EnvFileFormat } from "./EnvFileFormat";
import type { EnvIssue } from "./EnvIssue";

export type EnvParseOutput = { entries: Array<EnvEntry>, issues: Array<EnvIssue>, totalVars: number, emptyVars: number, duplicateKeys: Array<string>, 
/**
 * Entries serialized as JSON object (key -> value, comments/sections/empty excluded).
 */
asJson: string, 
/**
 * Entries normalized to KEY=VALUE format (comments/sections excluded).
 */
normalizedEnv: string, 
/**
 * The format that was actually used (useful when Auto was selected).
 */
detectedFormat: EnvFileFormat, };
