// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExprEvalOutput = { 
/**
 * The numeric result as a string (to preserve precision and handle display).
 */
result: string, 
/**
 * true if evaluation succeeded.
 */
success: boolean, 
/**
 * Human-readable error if evaluation failed.
 */
error: string | null, };
