// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExprEvalInput = { 
/**
 * The mathematical expression to evaluate (e.g. "sqrt(2) + 3^2").
 */
expression: string, };
