// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FakeDataOutput = { 
/**
 * Pretty-printed JSON array of generated records.
 */
json: string, error: string | null, };
