// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HashResult } from "./HashResult";

export type HashOutput = { results: Array<HashResult>, error: string | null, };
