// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HashResult = { 
/**
 * Algorithm name, e.g. "MD5", "SHA-256".
 */
algorithm: string, 
/**
 * Hash or HMAC output in the requested encoding.
 */
value: string, };
