// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HexMode } from "./HexMode";
import type { HexSeparator } from "./HexSeparator";

/**
 * Input for the Hex converter.
 */
export type HexInput = { text: string, mode: HexMode, separator: HexSeparator, };
