// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HtmlEntityEncodeType } from "./HtmlEntityEncodeType";
import type { HtmlEntityMode } from "./HtmlEntityMode";

/**
 * Input for the HTML entity encode/decode tool.
 */
export type HtmlEntityInput = { text: string, mode: HtmlEntityMode, encodeType: HtmlEntityEncodeType, };
