// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Named: &amp;, &lt;, &gt;, &quot;, &apos;. Numeric: &#38;, &#60;, &#62;, &#34;, &#39;.
 */
export type HtmlEntityEncodeType = "named" | "numeric";
