// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResizeOptions } from "./ResizeOptions";

export type ImageConvertInput = { data: string, inputFormat: string, outputFormat: string, quality: number, resize: ResizeOptions | null, rotate: number, flip: string, grayscale: boolean, };
