// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IpInspectOutput = { 
/**
 * "IPv4" or "IPv6"
 */
version: string, 
/**
 * e.g. "Private", "Public", "Loopback", "Link-local", "Multicast"
 */
ipType: string, 
/**
 * Plain-English explanation of what this address is used for
 */
description: string, 
/**
 * CIDR range this address belongs to, e.g. "192.168.0.0/16"
 */
range: string | null, 
/**
 * Defining RFC, e.g. "RFC 1918"
 */
rfc: string | null, 
/**
 * Dot-separated binary octets: "11000000.10101000.00000001.00000001"
 */
binary: string | null, 
/**
 * Uppercase hex without prefix: "C0A80101"
 */
hex: string | null, 
/**
 * Unsigned 32-bit decimal integer: 3232235777
 */
decimal: number | null, 
/**
 * Full expanded form: "fe80:0000:0000:0000:0000:0000:0000:0001"
 */
expanded: string | null, 
/**
 * Standard compressed form: "fe80::1"
 */
compressed: string | null, 
/**
 * If IPv4-mapped (::ffff:x.x.x.x), the embedded IPv4 address
 */
ipv4Mapped: string | null, error: string | null, };
