// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for the ISO 8601 formatter.
 */
export type Iso8601Input = { 
/**
 * The ISO 8601 string to parse (date, datetime, week date, ordinal, or duration).
 */
value: string, };
