// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output: parsed components and conversion formats.
 */
export type Iso8601Output = { isValid: boolean, 
/**
 * "Date", "DateTime", "DateTime with offset", "DateTime no offset",
 * "Week date", "Ordinal date", "Duration", "Invalid"
 */
inputType: string, date: string | null, time: string | null, offset: string | null, utcEquivalent: string | null, weekNumber: string | null, dayOfYear: number | null, quarter: number | null, dayOfWeek: string | null, asDateOnly: string | null, asWeekDate: string | null, asOrdinal: string | null, asUtc: string | null, asLocalOffset: string | null, durationYears: bigint | null, durationMonths: bigint | null, durationDays: bigint | null, durationHours: bigint | null, durationMinutes: bigint | null, durationSeconds: bigint | null, error: string | null, };
