// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for the JSON diff tool.
 */
export type JsonDiffInput = { 
/**
 * First JSON value (left side).
 */
left: string, 
/**
 * Second JSON value (right side).
 */
right: string, };
