// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversionTarget } from "./ConversionTarget";

export type JsonConvertInput = { value: string, target: ConversionTarget, 
/**
 * Root interface/type name (default: "Root").
 */
tsRootName: string | null, 
/**
 * Prefix interfaces with `export` (default: true).
 */
tsExport: boolean | null, 
/**
 * Make all fields optional (default: false).
 */
tsOptionalFields: boolean | null, 
/**
 * Root XML element name (default: "root").
 */
xmlRootElement: string | null, };
