// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single JSONPath match.
 */
export type JsonPathMatch = { 
/**
 * Canonical JSONPath for the matched value, e.g. "$['users'][0]['name']".
 */
path: string, 
/**
 * JSON-serialised matched value.
 */
value: string, 
/**
 * JSON value type: "string", "number", "boolean", "null", "object", "array".
 */
valueType: string, 
/**
 * 0-based match index.
 */
index: number, };
