// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JsonToCsvInput = { 
/**
 * JSON text (array of objects, single object, or array of primitives).
 */
value: string, 
/**
 * Output delimiter character: ",", "\t", "|", ";" (default: ",").
 */
delimiter: string, };
