// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output from the JSON validator.
 */
export type JsonValidateOutput = { isValid: boolean, error: string | null, errorLine: number | null, errorColumn: number | null, errorContext: string | null, rootType: string | null, depth: number | null, keyCount: number | null, valueCount: number | null, arrayCount: number | null, objectCount: number | null, stringCount: number | null, numberCount: number | null, booleanCount: number | null, nullCount: number | null, maxArrayLength: number | null, hasDuplicateKeys: boolean, formatted: string | null, };
