// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidationIssue } from "./ValidationIssue";

/**
 * Output from JSON Schema validation.
 */
export type JsonSchemaValidateOutput = { 
/**
 * Whether the document is valid against the schema.
 */
valid: boolean, 
/**
 * Total number of validation errors.
 */
errorCount: number, 
/**
 * List of individual validation issues.
 */
issues: Array<ValidationIssue>, 
/**
 * Set when the document or schema itself is not valid JSON.
 */
parseError: string | null, };
