// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for the JSONPath tool.
 */
export type JsonPathInput = { 
/**
 * JSON document to query.
 */
value: string, 
/**
 * JSONPath expression to apply.
 */
query: string, };
