// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Signing algorithm for the JWT.
 */
export type JwtAlgorithm = "HS256" | "HS384" | "HS512" | "none";
