// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JwtAlgorithm } from "./JwtAlgorithm";
import type { SecretEncoding } from "./SecretEncoding";

/**
 * Input for JWT build.
 */
export type JwtBuildInput = { algorithm: JwtAlgorithm, secret: string, secretEncoding: SecretEncoding, 
/**
 * Raw JSON string for payload (empty treated as "{}").
 */
payloadJson: string, includeIat: boolean, includeExp: boolean, 
/**
 * Seconds from now for exp when include_exp is true.
 */
expSeconds: number, 
/**
 * Optional extra header claims as JSON, e.g. {"kid": "my-key-id"}.
 */
extraHeaders: string, };
