// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecretEncoding } from "./SecretEncoding";

/**
 * Input for JWT decode.
 */
export type JwtDecodeInput = { 
/**
 * The JWT token string (header.payload.signature).
 */
token: string, 
/**
 * Optional secret for HMAC verification; empty string if not provided.
 */
secret: string, 
/**
 * How the secret is encoded when provided.
 */
secretEncoding: SecretEncoding, };
