// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineOperation } from "./LineOperation";

export type LineToolsInput = { text: string, 
/**
 * Ordered list of operations applied left-to-right.
 */
operations: Array<LineOperation>, 
/**
 * For Deduplicate: keep first occurrence (true) or last (false).
 */
keepFirst: boolean, 
/**
 * For Sort/Deduplicate: case-insensitive comparison.
 */
caseInsensitive: boolean, };
