// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LineToolsOutput = { result: string, inputLineCount: number, outputLineCount: number, changedCount: number, 
/**
 * Line ending style detected in input: "lf" | "crlf"
 */
lineEnding: string, };
