// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output: generated text and actual word/sentence/paragraph counts.
 */
export type LoremIpsumOutput = { result: string, wordCount: number, paragraphCount: number, sentenceCount: number, error: string | null, };
