// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output format: paragraphs, sentences, or words.
 */
export type LoremOutputType = "paragraphs" | "sentences" | "words";
