// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoremOutputType } from "./LoremOutputType";

/**
 * Input for the Lorem Ipsum generator.
 */
export type LoremIpsumInput = { outputType: LoremOutputType, count: number, startWithClassic: boolean, 
/**
 * Offset into the sentence/word pool so callers can vary text without changing other settings.
 */
offset: number, 
/**
 * Sentences per paragraph when `output_type` is `Paragraphs`. Clamped to 1–10 in `process`.
 */
sentencesPerParagraph: number, };
