// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output from Nano ID generation.
 */
export type NanoIdOutput = { 
/**
 * Generated IDs.
 */
ids: Array<string>, 
/**
 * Optional error message.
 */
error: string | null, };
