// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for Nano ID generation.
 */
export type NanoIdInput = { 
/**
 * Number of IDs to generate (1–100).
 */
count: number, 
/**
 * Length of each ID (4–256). Default: 21.
 */
size: number, 
/**
 * Optional custom alphabet. If None or empty, uses the default URL-safe alphabet.
 */
alphabet: string | null, };
