// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NatoPhoneticMode } from "./NatoPhoneticMode";

export type NatoPhoneticInput = { text: string, mode: NatoPhoneticMode, };
