// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PasswordStrength } from "./PasswordStrength";

/**
 * Output from the Password Generator tool.
 */
export type PasswordOutput = { passwords: Array<string>, strength: PasswordStrength, 
/**
 * Shannon entropy: length × log₂(alphabet_size). 0.0 when alphabet is empty.
 */
entropyBits: number, 
/**
 * Size of the effective alphabet used for generation.
 */
alphabetSize: number, error: string | null, };
