// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Strength tier based on Shannon entropy of the generated password.
 */
export type PasswordStrength = "Weak" | "Fair" | "Strong" | "VeryStrong";
