// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for the Password Generator tool.
 */
export type PasswordInput = { 
/**
 * Password length. Clamped to 4–256.
 */
length: number, 
/**
 * Number of passwords to generate. Clamped to 1–50.
 */
count: number, includeUppercase: boolean, includeLowercase: boolean, includeNumbers: boolean, includeSymbols: boolean, 
/**
 * When true, removes visually ambiguous chars: 0, O, o, 1, I, l.
 */
excludeAmbiguous: boolean, 
/**
 * Symbol set to use when include_symbols is true.
 * Defaults to "!@#$%^&*()-_=+[]{}|;:,.<>?" if empty.
 */
symbols: string, };
