// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Human-readable permissions for one class (owner / group / others).
 */
export type PermissionClass = { read: boolean, write: boolean, execute: boolean, label: string, };
