// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One query string key-value pair (decoded for display).
 */
export type QueryParam = { key: string, value: string, };
