// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RsaKeyFormat } from "./RsaKeyFormat";
import type { RsaKeySize } from "./RsaKeySize";

export type RsaKeygenInput = { keySize: RsaKeySize, format: RsaKeyFormat, };
