// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SemverCompareResult } from "./SemverCompareResult";

/**
 * Output from Semver processing.
 */
export type SemverOutput = { major: bigint | null, minor: bigint | null, patch: bigint | null, prerelease: string, buildMetadata: string, 
/**
 * Normalized semver string for the parsed version.
 */
canonical: string, compareResult: SemverCompareResult | null, compareError: string | null, rangeSatisfied: boolean | null, rangeError: string | null, bumpedMajor: string | null, bumpedMinor: string | null, bumpedPatch: string | null, error: string | null, };
