// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for the Slug Generator tool.
 */
export type SlugInput = { text: string, separator: string, lowercase: boolean, maxLength: number | null, };
