// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SqlFormatOutput = { result: string, lineCount: number, charCount: number, 
/**
 * Human-readable error if formatting failed (rare with sqlformat).
 */
error: string | null, };
