// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Runs JWT decode via instrument-core.
 */
async toolJwtDecode(input: JwtDecodeInput) : Promise<JwtDecodeOutput> {
    return await TAURI_INVOKE("tool_jwt_decode", { input });
},
/**
 * Runs JWT build via instrument-core.
 */
async toolJwtBuild(input: JwtBuildInput) : Promise<JwtBuildOutput> {
    return await TAURI_INVOKE("tool_jwt_build", { input });
},
/**
 * Encodes or decodes HTTP Basic Authorization header values via instrument-core.
 */
async toolBasicAuth(input: BasicAuthInput) : Promise<BasicAuthOutput> {
    return await TAURI_INVOKE("tool_basic_auth", { input });
},
/**
 * Runs combined hash (MD5, SHA-1/256/512, SHA3-256/512) via instrument-core.
 */
async toolHashProcess(input: HashInput) : Promise<HashOutput> {
    return await TAURI_INVOKE("tool_hash_process", { input });
},
/**
 * Runs ULID generation via instrument-core.
 */
async toolUlidProcess(input: UlidInput) : Promise<UlidOutput> {
    return await TAURI_INVOKE("tool_ulid_process", { input });
},
/**
 * Runs ULID inspection via instrument-core.
 */
async toolUlidInspect(input: UlidInspectInput) : Promise<UlidInspectOutput> {
    return await TAURI_INVOKE("tool_ulid_inspect", { input });
},
/**
 * Runs UUID generation via instrument-core.
 */
async toolUuidProcess(input: UuidInput) : Promise<UuidOutput> {
    return await TAURI_INVOKE("tool_uuid_process", { input });
},
/**
 * Runs UUID inspection via instrument-core.
 */
async toolUuidInspect(input: UuidInspectInput) : Promise<UuidInspectOutput> {
    return await TAURI_INVOKE("tool_uuid_inspect", { input });
},
/**
 * Runs API key generation via instrument-core.
 */
async toolApiKeyProcess(input: ApiKeyInput) : Promise<ApiKeyOutput> {
    return await TAURI_INVOKE("tool_api_key_process", { input });
},
/**
 * Runs Nano ID generation via instrument-core.
 */
async toolNanoidProcess(input: NanoIdInput) : Promise<NanoIdOutput> {
    return await TAURI_INVOKE("tool_nanoid_process", { input });
},
/**
 * Decodes X.509 / PEM certificates via instrument-core.
 */
async toolCertDecode(input: CertDecodeInput) : Promise<CertDecodeOutput> {
    return await TAURI_INVOKE("tool_cert_decode", { input });
},
/**
 * Runs AES-256-GCM encrypt/decrypt via instrument-core.
 */
async toolAesProcess(input: AesInput) : Promise<AesOutput> {
    return await TAURI_INVOKE("tool_aes_process", { input });
},
/**
 * Generates a TOTP code. Input/output values are never logged (sensitive tool).
 */
async toolTotpGenerate(input: TotpInput) : Promise<TotpOutput> {
    return await TAURI_INVOKE("tool_totp_generate", { input });
},
/**
 * Runs Password generation via instrument-core.
 */
async toolPasswordProcess(input: PasswordInput) : Promise<PasswordOutput> {
    return await TAURI_INVOKE("tool_password_process", { input });
},
/**
 * Runs Passphrase generation via instrument-core.
 */
async toolPassphraseProcess(input: PassphraseInput) : Promise<PassphraseOutput> {
    return await TAURI_INVOKE("tool_passphrase_process", { input });
},
/**
 * Runs case conversion via instrument-core.
 */
async toolCaseProcess(input: CaseInput) : Promise<CaseOutput> {
    return await TAURI_INVOKE("tool_case_process", { input });
},
/**
 * Runs word counting via instrument-core.
 */
async toolWordCounterProcess(input: WordCounterInput) : Promise<WordCounterOutput> {
    return await TAURI_INVOKE("tool_word_counter_process", { input });
},
/**
 * Runs Unicode character inspection via instrument-core.
 */
async toolUnicodeInspect(input: UnicodeInspectInput) : Promise<UnicodeInspectOutput> {
    return await TAURI_INVOKE("tool_unicode_inspect", { input });
},
/**
 * Runs slug generation via instrument-core.
 */
async toolSlugGenerate(input: SlugInput) : Promise<SlugOutput> {
    return await TAURI_INVOKE("tool_slug_generate", { input });
},
/**
 * Converts text to/from NATO phonetic alphabet.
 */
async toolNatoPhoneticProcess(input: NatoPhoneticInput) : Promise<NatoPhoneticOutput> {
    return await TAURI_INVOKE("tool_nato_phonetic_process", { input });
},
/**
 * Runs string escape/unescape via instrument-core.
 */
async toolStringEscaperProcess(input: StringEscaperInput) : Promise<StringEscaperOutput> {
    return await TAURI_INVOKE("tool_string_escaper_process", { input });
},
/**
 * Runs find and replace via instrument-core.
 */
async toolFindReplaceProcess(input: FindReplaceInput) : Promise<FindReplaceOutput> {
    return await TAURI_INVOKE("tool_find_replace_process", { input });
},
/**
 * Runs lorem ipsum generation via instrument-core.
 */
async toolLoremIpsumProcess(input: LoremIpsumInput) : Promise<LoremIpsumOutput> {
    return await TAURI_INVOKE("tool_lorem_ipsum_process", { input });
},
/**
 * Runs line-by-line text diff via instrument-core.
 */
async toolTextDiffProcess(input: TextDiffInput) : Promise<TextDiffOutput> {
    return await TAURI_INVOKE("tool_text_diff_process", { input });
},
/**
 * Runs line-level text tools via instrument-core.
 */
async toolLineToolsProcess(input: LineToolsInput) : Promise<LineToolsOutput> {
    return await TAURI_INVOKE("tool_line_tools_process", { input });
},
/**
 * Generates fake records from a field schema (JSON output).
 */
async toolFakeDataProcess(input: FakeDataInput) : Promise<FakeDataOutput> {
    return await TAURI_INVOKE("tool_fake_data_process", { input });
},
/**
 * Parses and validates .env content via instrument-core.
 */
async toolEnvParse(input: EnvParseInput) : Promise<EnvParseOutput> {
    return await TAURI_INVOKE("tool_env_parse", { input });
},
/**
 * Runs timestamp conversion via instrument-core.
 */
async toolTimestampProcess(input: TimestampInput) : Promise<TimestampOutput> {
    return await TAURI_INVOKE("tool_timestamp_process", { input });
},
/**
 * Runs timezone conversion via instrument-core.
 */
async toolTimezoneProcess(input: TimezoneInput) : Promise<TimezoneOutput> {
    return await TAURI_INVOKE("tool_timezone_process", { input });
},
/**
 * Runs ISO 8601 parse/format via instrument-core.
 */
async toolIso8601Process(input: Iso8601Input) : Promise<Iso8601Output> {
    return await TAURI_INVOKE("tool_iso8601_process", { input });
},
/**
 * Parses a cron expression and returns next run times (UTC).
 */
async toolCronProcess(input: CronInput) : Promise<CronOutput> {
    return await TAURI_INVOKE("tool_cron_process", { input });
},
/**
 * Runs Base64 encode or decode via instrument-core.
 */
async toolBase64Process(input: Base64Input) : Promise<Base64Output> {
    return await TAURI_INVOKE("tool_base64_process", { input });
},
/**
 * Runs URL percent-encode or decode via instrument-core.
 */
async toolUrlEncodeProcess(input: UrlEncodeInput) : Promise<UrlEncodeOutput> {
    return await TAURI_INVOKE("tool_url_encode_process", { input });
},
/**
 * Runs HTML entity encode or decode via instrument-core.
 */
async toolHtmlEntityProcess(input: HtmlEntityInput) : Promise<HtmlEntityOutput> {
    return await TAURI_INVOKE("tool_html_entity_process", { input });
},
/**
 * Runs Hex encode or decode via instrument-core.
 */
async toolHexProcess(input: HexInput) : Promise<HexOutput> {
    return await TAURI_INVOKE("tool_hex_process", { input });
},
/**
 * Converts a colour string to HEX, RGB, HSL, HSB, and CSS name.
 */
async toolColorConvert(input: ColorInput) : Promise<ColorOutput> {
    return await TAURI_INVOKE("tool_color_convert", { input });
},
/**
 * Generates a QR code SVG from input text.
 */
async toolQrGenerate(input: QrCodeInput) : Promise<QrCodeOutput> {
    return await TAURI_INVOKE("tool_qr_generate", { input });
},
/**
 * Runs JSON format/minify via instrument-core.
 */
async toolJsonFormat(input: JsonFormatInput) : Promise<JsonFormatOutput> {
    return await TAURI_INVOKE("tool_json_format", { input });
},
/**
 * Runs JSON validation and structure summary via instrument-core.
 */
async toolJsonValidate(input: JsonValidateInput) : Promise<JsonValidateOutput> {
    return await TAURI_INVOKE("tool_json_validate", { input });
},
/**
 * Validates a JSON document against a JSON Schema via instrument-core.
 */
async toolJsonSchemaValidate(input: JsonSchemaValidateInput) : Promise<JsonSchemaValidateOutput> {
    return await TAURI_INVOKE("tool_json_schema_validate", { input });
},
/**
 * Runs JSON diff (compare two JSON values) via instrument-core.
 */
async toolJsonDiff(input: JsonDiffInput) : Promise<JsonDiffOutput> {
    return await TAURI_INVOKE("tool_json_diff", { input });
},
/**
 * Runs JSONPath query against a JSON document via instrument-core.
 */
async toolJsonPath(input: JsonPathInput) : Promise<JsonPathOutput> {
    return await TAURI_INVOKE("tool_json_path", { input });
},
/**
 * Runs JSON conversion (YAML, TypeScript, CSV, XML) via instrument-core.
 */
async toolJsonConvert(input: JsonConvertInput) : Promise<JsonConvertOutput> {
    return await TAURI_INVOKE("tool_json_convert", { input });
},
/**
 * Converts between JSON, YAML, and TOML via instrument-core.
 */
async toolConfigConvert(input: ConfigConvertInput) : Promise<ConfigConvertOutput> {
    return await TAURI_INVOKE("tool_config_convert", { input });
},
async toolUrlParse(input: UrlParseInput) : Promise<UrlParseOutput> {
    return await TAURI_INVOKE("tool_url_parse", { input });
},
async toolCidrCalculate(input: CidrInput) : Promise<CidrOutput> {
    return await TAURI_INVOKE("tool_cidr_calculate", { input });
},
async toolUaParse(input: UaParseInput) : Promise<UaParseOutput> {
    return await TAURI_INVOKE("tool_ua_parse", { input });
},
/**
 * Runs base conversion via instrument-core.
 */
async toolBaseConverterProcess(input: BaseConverterInput) : Promise<BaseConverterOutput> {
    return await TAURI_INVOKE("tool_base_converter_process", { input });
},
/**
 * Runs bitwise operations via instrument-core.
 */
async toolBitwiseProcess(input: BitwiseInput) : Promise<BitwiseOutput> {
    return await TAURI_INVOKE("tool_bitwise_process", { input });
},
/**
 * Parses Unix permission strings (octal or symbolic) via instrument-core.
 */
async toolChmodProcess(input: ChmodInput) : Promise<ChmodOutput> {
    return await TAURI_INVOKE("tool_chmod_process", { input });
},
/**
 * Computes WCAG contrast ratio for a foreground/background colour pair.
 */
async toolColorContrastProcess(input: ColorContrastInput) : Promise<ColorContrastOutput> {
    return await TAURI_INVOKE("tool_color_contrast_process", { input });
},
/**
 * Parse semver, compare versions, check version ranges, and bump major/minor/patch.
 */
async toolSemverProcess(input: SemverInput) : Promise<SemverOutput> {
    return await TAURI_INVOKE("tool_semver_process", { input });
},
/**
 * Converts a value between units in a given category.
 */
async toolUnitConvert(input: UnitConverterInput) : Promise<UnitConverterOutput> {
    return await TAURI_INVOKE("tool_unit_convert", { input });
},
/**
 * Runs a regex test via regex-core for desktop (native) builds.
 */
async toolRegexTest(req: RegexRequest) : Promise<Result<MatchResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tool_regex_test", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns a structured explanation of the regex pattern (HIR tokens).
 */
async toolRegexExplain(req: ExplainRequest) : Promise<Result<ExplainToken[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tool_regex_explain", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Runs SQL formatting via instrument-core.
 */
async toolSqlFormat(input: SqlFormatInput) : Promise<SqlFormatOutput> {
    return await TAURI_INVOKE("tool_sql_format", { input });
},
/**
 * Runs CSV to JSON conversion via instrument-core.
 */
async toolCsvToJson(input: CsvToJsonInput) : Promise<CsvToJsonOutput> {
    return await TAURI_INVOKE("tool_csv_to_json", { input });
},
/**
 * Runs JSON to CSV conversion via instrument-core.
 */
async toolJsonToCsv(input: JsonToCsvInput) : Promise<JsonToCsvOutput> {
    return await TAURI_INVOKE("tool_json_to_csv", { input });
},
/**
 * Parses CSV into structured headers + rows for table rendering.
 */
async toolCsvPreview(input: CsvPreviewInput) : Promise<CsvPreviewOutput> {
    return await TAURI_INVOKE("tool_csv_preview", { input });
},
async toolXmlFormat(input: XmlFormatInput) : Promise<XmlFormatOutput> {
    return await TAURI_INVOKE("tool_xml_format", { input });
},
async toolHtmlFormat(input: HtmlFormatInput) : Promise<HtmlFormatOutput> {
    return await TAURI_INVOKE("tool_html_format", { input });
},
async toolYamlFormat(input: YamlFormatInput) : Promise<YamlFormatOutput> {
    return await TAURI_INVOKE("tool_yaml_format", { input });
},
async toolExpressionEval(input: ExprEvalInput) : Promise<ExprEvalOutput> {
    return await TAURI_INVOKE("tool_expression_eval", { input });
},
/**
 * Converts image bytes between formats with optional transforms.
 */
async toolImageConvert(input: ImageConvertInput) : Promise<ImageConvertOutput> {
    return await TAURI_INVOKE("tool_image_convert", { input });
},
/**
 * Called from the frontend whenever the favourites list changes.
 */
async updateTrayMenu(tools: TrayToolItem[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_tray_menu", { tools }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Show or hide the tray icon based on user preference.
 */
async setTrayVisible(visible: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_tray_visible", { visible }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open the popover to a specific tool (e.g. hotkey / programmatic).
 */
async openPopover(toolId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_popover", { toolId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Initial tool id for the popover webview (set before first open).
 */
async getPopoverTool() : Promise<string> {
    return await TAURI_INVOKE("get_popover_tool");
},
/**
 * Show main window, navigate to tool, hide popover.
 */
async openMainAndNavigate(toolId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_main_and_navigate", { toolId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One-shot clipboard text captured when the tray opened the popover (for auto-paste before mount).
 */
async consumePopoverClipboardSeed() : Promise<string | null> {
    return await TAURI_INVOKE("consume_popover_clipboard_seed");
},
/**
 * Enable or disable the global hotkey at runtime (from Settings toggle).
 */
async setGlobalHotkeyEnabled(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_global_hotkey_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the current clipboard text — used by the popover picker after selecting a tool.
 */
async readClipboardText() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_clipboard_text") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AesInput = { text: string; passphrase: string; 
/**
 * `"encrypt"` or `"decrypt"`.
 */
mode: string }
export type AesOutput = { result: string; error: string | null }
/**
 * Character set used for API key generation.
 */
export type ApiKeyCharset = "alphanumeric" | "alphaOnly" | "hexOnly" | "urlSafe"
/**
 * Output string format for an API key.
 */
export type ApiKeyFormat = "raw" | "grouped" | "prefixed"
/**
 * Input for the API Key Generator tool.
 */
export type ApiKeyInput = { 
/**
 * `u32` so tauri-specta TS export avoids bigint (forbidden for IPC).
 */
count: number; length: number; prefix: string; format: ApiKeyFormat; charset: ApiKeyCharset }
/**
 * Output from the API Key Generator tool.
 */
export type ApiKeyOutput = { keys: string[]; error: string | null }
/**
 * Input for the Base64 tool: text to encode or decode, engine choice, and mode.
 */
export type Base64Input = { text: string; urlSafe: boolean; mode: Base64Mode }
/**
 * Whether to encode or decode.
 */
export type Base64Mode = "encode" | "decode"
/**
 * Output: result string, counts, and optional error message.
 */
export type Base64Output = { result: string; byteCount: number; charCount: number; error: string | null }
/**
 * Input for the base converter.
 */
export type BaseConverterInput = { value: string; fromBase: NumberBase; bitWidth: BitWidth; uppercaseHex: boolean }
/**
 * Output: the value in every supported base.
 */
export type BaseConverterOutput = { decimal: string; hexadecimal: string; binary: string; binaryGrouped: string; octal: string; base32: string; base36: string; bitLength: number; isNegative: boolean; error: string | null }
/**
 * Input for the Basic Auth Header tool.
 */
export type BasicAuthInput = { mode: BasicAuthMode; username: string; password: string; header: string }
/**
 * Whether to encode credentials to a header or decode an existing header.
 */
export type BasicAuthMode = "encode" | "decode"
/**
 * Output: always all fields present; unused strings are empty on error or opposite mode.
 */
export type BasicAuthOutput = { encoded: string; decodedUsername: string; decodedPassword: string; rawBase64: string; error: string | null }
/**
 * Bit width for binary output (padding and grouping).
 */
export type BitWidth = "auto" | "bit8" | "bit16" | "bit32" | "bit64"
/**
 * Input base for parsing value A and B.
 */
export type BitwiseBase = "decimal" | "hexadecimal" | "binary" | "octal"
/**
 * Input for the bitwise calculator.
 */
export type BitwiseInput = { valueA: string; valueB: string; fromBase: BitwiseBase; bitWidth: BitwiseWidth; shiftAmount: number }
/**
 * Output: two-operand ops, single-operand ops, and bit analysis of A.
 */
export type BitwiseOutput = { and: BitwiseResult | null; or: BitwiseResult | null; xor: BitwiseResult | null; nand: BitwiseResult | null; nor: BitwiseResult | null; notA: BitwiseResult | null; shiftLeft: BitwiseResult | null; shiftRight: BitwiseResult | null; rotateLeft: BitwiseResult | null; rotateRight: BitwiseResult | null; bitCountA: number | null; leadingZerosA: number | null; trailingZerosA: number | null; isPowerOfTwoA: boolean | null; error: string | null }
/**
 * One operation result in multiple bases.
 */
export type BitwiseResult = { decimal: string; hexadecimal: string; binary: string; binaryGrouped: string; octal: string }
/**
 * Bit width for all operations (determines integer type: u8, u16, u32, u64).
 */
export type BitwiseWidth = "bit8" | "bit16" | "bit32" | "bit64"
/**
 * Input for the Text Case Converter tool.
 */
export type CaseInput = { text: string }
/**
 * Output for the Text Case Converter tool: all case variants at once.
 */
export type CaseOutput = { camelCase: string; pascalCase: string; snakeCase: string; screamingCase: string; kebabCase: string; titleCase: string; upperCase: string; lowerCase: string; dotCase: string; pathCase: string; wordCount: number; error: string | null }
export type CertDecodeInput = { 
/**
 * PEM-encoded certificate (one or chain).
 */
pem: string }
export type CertDecodeOutput = { certificates: CertInfo[]; error: string | null }
export type CertInfo = { subject: string; subjectFields: DnField[]; issuer: string; issuerFields: DnField[]; serialNumber: string; notBefore: string; notAfter: string; isExpired: boolean; expiryWarning: boolean; daysUntilExpiry: number; signatureAlgorithm: string; publicKeyAlgorithm: string; publicKeySize: number | null; sans: string[]; isCa: boolean; keyUsages: string[]; extendedKeyUsages: string[]; fingerprintSha256: string; version: number }
/**
 * Type of change between left and right.
 */
export type ChangeType = 
/**
 * Key exists in right but not in left.
 */
"added" | 
/**
 * Key exists in left but not in right.
 */
"removed" | 
/**
 * Same key, different value.
 */
"changed" | 
/**
 * Same key, different JSON type.
 */
"typeChanged"
/**
 * Input — the raw permission string (octal "755", symbolic "rwxr-xr-x", etc.)
 */
export type ChmodInput = { value: string }
/**
 * Full output.
 */
export type ChmodOutput = { octal: string; symbolic: string; decimal: number; chmodCommand: string; owner: PermissionClass; group: PermissionClass; others: PermissionClass; setuid: boolean; setgid: boolean; sticky: boolean; error: string | null }
export type CidrInput = { cidr: string }
export type CidrOutput = { networkAddress: string; broadcastAddress: string | null; subnetMask: string; wildcardMask: string; firstHost: string | null; lastHost: string | null; totalHosts: number; usableHosts: number; prefixLength: number; ipVersion: number; ipClass: string | null; isPrivate: boolean; isLoopback: boolean; binaryMask: string; 
/**
 * Number of host bits.
 */
hostBits: number; 
/**
 * Number of wildcard bits.
 */
wildcardBits: number; 
/**
 * IPv6 scope classification.
 */
ipv6Scope: string | null; 
/**
 * Human-readable note for special prefix lengths.
 */
specialNote: string | null; 
/**
 * Subnet split preview.
 */
subnetSplit: SubnetSplit | null; error: string | null }
export type ColorContrastInput = { 
/**
 * Foreground colour — 3 or 6-digit hex, with or without `#`.
 */
foreground: string; 
/**
 * Background colour — 3 or 6-digit hex, with or without `#`.
 */
background: string }
export type ColorContrastOutput = { 
/**
 * Contrast ratio, e.g. 4.54.
 */
ratio: number; 
/**
 * Human-readable ratio string, e.g. "4.54:1".
 */
ratioDisplay: string; 
/**
 * WCAG AA — normal text (≥4.5:1).
 */
aaNormal: boolean; 
/**
 * WCAG AA — large text / UI components (≥3.0:1).
 */
aaLarge: boolean; 
/**
 * WCAG AAA — normal text (≥7.0:1).
 */
aaaNormal: boolean; 
/**
 * WCAG AAA — large text (≥4.5:1).
 */
aaaLarge: boolean; 
/**
 * Normalised foreground hex (always `#RRGGBB` uppercase).
 */
foregroundHex: string; 
/**
 * Normalised background hex (always `#RRGGBB` uppercase).
 */
backgroundHex: string; 
/**
 * Set when either colour cannot be parsed.
 */
error: string | null }
/**
 * Input for the colour converter.
 */
export type ColorInput = { value: string }
/**
 * Output — all four colour formats plus an optional CSS name.
 */
export type ColorOutput = { hex: string; rgb: string; hsl: string; hsb: string; name: string | null; error: string | null }
/**
 * Input for the Config Converter tool.
 */
export type ConfigConvertInput = { value: string; from: ConfigFormat; to: ConfigFormat; 
/**
 * JSON/YAML output indent (2 or 4). Ignored when output is TOML.
 */
indent: number; 
/**
 * Sort keys alphabetically. Only applies to JSON output.
 */
sortKeys: boolean }
/**
 * Output from the Config Converter tool.
 */
export type ConfigConvertOutput = { result: string; isValidInput: boolean; error: string | null; 
/**
 * Line number of parse error (1-based), if available.
 */
errorLine: number | null; 
/**
 * Column number of parse error (1-based), if available.
 */
errorColumn: number | null; lineCount: number; charCount: number }
/**
 * Supported configuration formats.
 */
export type ConfigFormat = "Json" | "Yaml" | "Toml"
export type ConversionTarget = "yaml" | "typeScript" | "csv" | "xml"
export type CronInput = { expression: string; 
/**
 * How many upcoming run times to return (default 5, max 10).
 */
count: number | null }
export type CronOutput = { isValid: boolean; description: string; 
/**
 * Next N run times as ISO 8601 strings (UTC).
 */
nextRuns: string[]; error: string | null }
export type CsvOutputFormat = 
/**
 * Array of objects: one object per row, using headers (or synthetic column names) as keys.
 */
"arrayOfObjects" | 
/**
 * Array of arrays: each row is a string array.
 */
"arrayOfArrays"
/**
 * Input for the CSV Previewer.
 */
export type CsvPreviewInput = { text: string; hasHeaders: boolean; delimiter: string; 
/**
 * Maximum rows to return (default 1000).
 */
maxRows: number | null }
/**
 * Parsed CSV output ready for table rendering.
 */
export type CsvPreviewOutput = { 
/**
 * Column headers (empty when `has_headers` is false).
 */
headers: string[]; 
/**
 * Data rows (up to `max_rows`).
 */
rows: string[][]; 
/**
 * Total rows in the file (may exceed `rows.len()` when truncated).
 */
totalRows: number; truncated: boolean; error: string | null }
export type CsvToJsonInput = { 
/**
 * Raw CSV text.
 */
value: string; 
/**
 * Treat first row as header names.
 */
hasHeaders: boolean; 
/**
 * Single-character delimiter: ",", "\t", "|", ";" etc.
 */
delimiter: string; 
/**
 * Output layout.
 */
outputFormat: CsvOutputFormat }
export type CsvToJsonOutput = { 
/**
 * Pretty-printed JSON string.
 */
result: string; 
/**
 * Number of data rows (excluding header when has_headers == true).
 */
rowCount: number; 
/**
 * Number of columns detected (max across rows / headers).
 */
columnCount: number; 
/**
 * Error message if parsing failed.
 */
error: string | null }
/**
 * A single diff change at a path.
 */
export type DiffChange = { 
/**
 * Dot-notation path, e.g. "user.name", "items[0].price".
 */
path: string; changeType: ChangeType; 
/**
 * JSON-serialised value on the left (None for Added).
 */
leftValue: string | null; 
/**
 * JSON-serialised value on the right (None for Removed).
 */
rightValue: string | null }
export type DiffGranularity = "line" | "word" | "char"
export type DnField = { label: string; value: string }
export type EnvEntry = { key: string; value: string; rawValue: string; lineNumber: number; isEmptyValue: boolean; isComment: boolean; isQuoted: boolean; 
/**
 * For .ini files: the section this key belongs to. None for .env/.properties.
 */
section: string | null; 
/**
 * True if this entry is a section header.
 */
isSection: boolean }
export type EnvFileFormat = 
/**
 * Auto-detect from content.
 */
"auto" | 
/**
 * KEY=VALUE, # comments, quoted values.
 */
"env" | 
/**
 * KEY=VALUE or KEY: VALUE, # and ! comments, trimmed values.
 */
"properties" | 
/**
 * [Section] headers, KEY=VALUE, # and ; comments.
 */
"ini"
export type EnvIssue = { lineNumber: number; kind: string; severity: string; message: string; key: string | null }
export type EnvParseInput = { content: string; format?: EnvFileFormat; 
/**
 * If true, mask values that look like secrets.
 */
maskValues?: boolean }
export type EnvParseOutput = { entries: EnvEntry[]; issues: EnvIssue[]; totalVars: number; emptyVars: number; duplicateKeys: string[]; 
/**
 * Entries serialized as JSON object (key -> value, comments/sections/empty excluded).
 */
asJson: string; 
/**
 * Entries normalized to KEY=VALUE format (comments/sections excluded).
 */
normalizedEnv: string; 
/**
 * The format that was actually used (useful when Auto was selected).
 */
detectedFormat: EnvFileFormat }
/**
 * Escape or unescape.
 */
export type EscapeMode = "escape" | "unescape"
/**
 * Target format: JSON, Regex, HTML, SQL, Shell, CSV.
 */
export type EscapeTarget = "json" | "regex" | "html" | "sql" | "shell" | "csv"
export type ExplainRequest = { pattern: string; engine: string }
export type ExplainToken = { kind: string; label: string; description: string; depth: number }
export type ExprEvalInput = { 
/**
 * The mathematical expression to evaluate (e.g. "sqrt(2) + 3^2").
 */
expression: string }
export type ExprEvalOutput = { 
/**
 * The numeric result as a string (to preserve precision and handle display).
 */
result: string; 
/**
 * true if evaluation succeeded.
 */
success: boolean; 
/**
 * Human-readable error if evaluation failed.
 */
error: string | null }
export type FakeDataInput = { fields: FakeField[]; 
/**
 * Number of records to generate (capped at 500).
 */
count: number }
export type FakeDataOutput = { 
/**
 * Pretty-printed JSON array of generated records.
 */
json: string; error: string | null }
/**
 * One field definition in the schema.
 */
export type FakeField = { 
/**
 * The key name in the output JSON object.
 */
name: string; 
/**
 * The data type identifier (e.g. "email", "city", "uuid").
 */
fieldType: string; 
/**
 * Optional parameters for parameterised types.
 */
params: JsonValue | null }
/**
 * Input for the Find & Replace tool.
 */
export type FindReplaceInput = { text: string; find: string; replace: string; caseSensitive: boolean; wholeWord: boolean; regexMode: boolean; replaceAll: boolean }
/**
 * Output: result string, total matches found, number replaced, match ranges, optional error.
 * match_ranges: [start_byte, end_byte] of each match in the ORIGINAL text.
 * Empty when find is empty, no matches, or on error.
 */
export type FindReplaceOutput = { result: string; matchCount: number; replacedCount: number; matchRanges: ([number, number])[]; error: string | null }
export type HashInput = { 
/**
 * Text to hash (UTF-8).
 */
text: string; 
/**
 * If true, empty/whitespace-only input is hashed; otherwise all results are empty.
 */
hashEmpty: boolean; 
/**
 * Output encoding for all algorithms.
 */
outputFormat: HashOutputFormat; 
/**
 * If true and format is Hex, return uppercase hex. Ignored for Base64/Base64url.
 */
uppercase: boolean; 
/**
 * Optional HMAC secret key. When non-empty, all algorithms run as HMAC-<algo>.
 */
hmacKey: string }
export type HashOutput = { results: HashResult[]; error: string | null }
export type HashOutputFormat = "hex" | "base64" | "base64Url"
export type HashResult = { 
/**
 * Algorithm name, e.g. "MD5", "SHA-256".
 */
algorithm: string; 
/**
 * Hash or HMAC output in the requested encoding.
 */
value: string }
/**
 * Input for the Hex converter.
 */
export type HexInput = { text: string; mode: HexMode; separator: HexSeparator }
/**
 * Conversion direction.
 */
export type HexMode = "textToHex" | "hexToText"
/**
 * Output for the Hex converter.
 */
export type HexOutput = { result: string; byteCount: number; error: string | null }
/**
 * Separator style when encoding bytes to hex.
 */
export type HexSeparator = "none" | "space" | "colon" | "dash"
/**
 * Named: &amp;, &lt;, &gt;, &quot;, &apos;. Numeric: &#38;, &#60;, &#62;, &#34;, &#39;.
 */
export type HtmlEntityEncodeType = "named" | "numeric"
/**
 * Input for the HTML entity encode/decode tool.
 */
export type HtmlEntityInput = { text: string; mode: HtmlEntityMode; encodeType: HtmlEntityEncodeType }
/**
 * Whether to encode or decode.
 */
export type HtmlEntityMode = "encode" | "decode"
/**
 * Output: result string, count of entities encoded/decoded, and optional error.
 */
export type HtmlEntityOutput = { result: string; entitiesFound: number; error: string | null }
export type HtmlFormatInput = { 
/**
 * Raw HTML to format.
 */
code: string; 
/**
 * Spaces per indent level, or `0` for tabs.
 */
indentSize: number; 
/**
 * Prefer each attribute on its own line when a tag has multiple attributes.
 */
wrapAttributes: boolean; 
/**
 * Soft wrap width (used by the formatter layout engine; strongest effect with wrap attributes on).
 */
printWidth: number }
export type HtmlFormatOutput = { formatted: string; error: string | null }
export type ImageConvertInput = { data: string; inputFormat: string; outputFormat: string; quality: number; resize: ResizeOptions | null; rotate: number; flip: string; grayscale: boolean }
export type ImageConvertOutput = { data: string; format: string; width: number; height: number; sizeBytes: number; error: string | null }
/**
 * Indentation style for Pretty mode.
 */
export type IndentStyle = 
/**
 * Two spaces per indent level.
 */
"spaces2" | 
/**
 * Four spaces per indent level.
 */
"spaces4" | 
/**
 * One tab per indent level.
 */
"tab"
/**
 * Input for the ISO 8601 formatter.
 */
export type Iso8601Input = { 
/**
 * The ISO 8601 string to parse (date, datetime, week date, ordinal, or duration).
 */
value: string }
/**
 * Output: parsed components and conversion formats.
 */
export type Iso8601Output = { isValid: boolean; 
/**
 * "Date", "DateTime", "DateTime with offset", "DateTime no offset",
 * "Week date", "Ordinal date", "Duration", "Invalid"
 */
inputType: string; date: string | null; time: string | null; offset: string | null; utcEquivalent: string | null; weekNumber: string | null; dayOfYear: number | null; quarter: number | null; dayOfWeek: string | null; asDateOnly: string | null; asWeekDate: string | null; asOrdinal: string | null; asUtc: string | null; asLocalOffset: string | null; durationYears: number | null; durationMonths: number | null; durationDays: number | null; durationHours: number | null; durationMinutes: number | null; durationSeconds: number | null; error: string | null }
export type JsonConvertInput = { value: string; target: ConversionTarget; 
/**
 * Root interface/type name (default: "Root").
 */
tsRootName: string | null; 
/**
 * Prefix interfaces with `export` (default: true).
 */
tsExport: boolean | null; 
/**
 * Make all fields optional (default: false).
 */
tsOptionalFields: boolean | null; 
/**
 * Root XML element name (default: "root").
 */
xmlRootElement: string | null }
export type JsonConvertOutput = { result: string; isValidJson: boolean; target: ConversionTarget; error: string | null; 
/**
 * Non-fatal warnings about lossy transforms, etc.
 */
warning: string | null; lineCount: number; charCount: number }
/**
 * A single line in the annotated diff output.
 */
export type JsonDiffAnnotatedLine = { 
/**
 * `u32` (not `usize`) so tauri-specta TypeScript export avoids bigint, which IPC forbids.
 */
lineNumber: number; 
/**
 * Line text without prefix.
 */
content: string; annotation: JsonDiffLineAnnotation }
/**
 * Input for the JSON diff tool.
 */
export type JsonDiffInput = { 
/**
 * First JSON value (left side).
 */
left: string; 
/**
 * Second JSON value (right side).
 */
right: string }
/**
 * Annotation for a single line in the diff view.
 */
export type JsonDiffLineAnnotation = 
/**
 * Line unchanged between left and right.
 */
"unchanged" | 
/**
 * Line only in right (added); right panel only.
 */
"added" | 
/**
 * Line only in left (removed); left panel only.
 */
"removed" | 
/**
 * Line present in both but value differs.
 */
"changed"
/**
 * Output from the JSON diff tool.
 */
export type JsonDiffOutput = { isIdentical: boolean; leftValid: boolean; rightValid: boolean; changes: DiffChange[]; 
/**
 * `u32` for tauri-specta export (no bigint in TS bindings).
 */
addedCount: number; removedCount: number; changedCount: number; unchangedCount: number; leftAnnotated: JsonDiffAnnotatedLine[]; rightAnnotated: JsonDiffAnnotatedLine[]; error: string | null }
/**
 * Input for the JSON formatter.
 */
export type JsonFormatInput = { 
/**
 * Raw JSON string to format.
 */
value: string; 
/**
 * Output format mode.
 */
mode: JsonFormatMode; 
/**
 * Indentation style in Pretty mode.
 */
indent: IndentStyle; 
/**
 * If true, sort object keys alphabetically.
 */
sortKeys: boolean }
/**
 * Format mode for JSON output.
 */
export type JsonFormatMode = 
/**
 * Formatted with indentation.
 */
"pretty" | 
/**
 * Single line, no whitespace.
 */
"minify" | 
/**
 * Single line, minimal spaces after `:` and `,`.
 */
"compact"
/**
 * Output from the JSON formatter.
 */
export type JsonFormatOutput = { result: string; isValid: boolean; 
/**
 * `u32` (not `usize`) so tauri-specta avoids bigint in TS export.
 */
lineCount: number; charCount: number; sizeBytes: number; sizeOriginalBytes: number; compressionRatio: number | null; error: string | null; errorLine: number | null; errorColumn: number | null }
/**
 * Input for the JSONPath tool.
 */
export type JsonPathInput = { 
/**
 * JSON document to query.
 */
value: string; 
/**
 * JSONPath expression to apply.
 */
query: string }
/**
 * A single JSONPath match.
 */
export type JsonPathMatch = { 
/**
 * Canonical JSONPath for the matched value, e.g. "$['users'][0]['name']".
 */
path: string; 
/**
 * JSON-serialised matched value.
 */
value: string; 
/**
 * JSON value type: "string", "number", "boolean", "null", "object", "array".
 */
valueType: string; 
/**
 * 0-based match index.
 */
index: number }
/**
 * Output from the JSONPath tool.
 */
export type JsonPathOutput = { isValidJson: boolean; isValidQuery: boolean; matches: JsonPathMatch[]; matchCount: number; error: string | null; 
/**
 * Pretty-printed full JSON document (no inline annotations yet).
 */
annotatedDocument: string | null }
/**
 * Input for JSON Schema validation.
 */
export type JsonSchemaValidateInput = { 
/**
 * The JSON document to validate (raw string).
 */
document: string; 
/**
 * The JSON Schema to validate against (raw string).
 */
schema: string; 
/**
 * Which schema draft to use (defaults to draft7).
 */
draft?: SchemaDraft }
/**
 * Output from JSON Schema validation.
 */
export type JsonSchemaValidateOutput = { 
/**
 * Whether the document is valid against the schema.
 */
valid: boolean; 
/**
 * Total number of validation errors.
 */
errorCount: number; 
/**
 * List of individual validation issues.
 */
issues: ValidationIssue[]; 
/**
 * Set when the document or schema itself is not valid JSON.
 */
parseError: string | null }
export type JsonToCsvInput = { 
/**
 * JSON text (array of objects, single object, or array of primitives).
 */
value: string; 
/**
 * Output delimiter character: ",", "\t", "|", ";" (default: ",").
 */
delimiter: string }
export type JsonToCsvOutput = { 
/**
 * CSV text output.
 */
result: string; 
/**
 * Number of data rows (excluding header).
 */
rowCount: number; 
/**
 * Number of columns.
 */
columnCount: number; 
/**
 * Non-fatal warning (e.g. "Nested objects serialised as JSON").
 */
warning: string | null; 
/**
 * Error message if conversion failed.
 */
error: string | null }
/**
 * Input for the JSON validator.
 */
export type JsonValidateInput = { 
/**
 * Raw JSON string to validate.
 */
value: string }
/**
 * Output from the JSON validator.
 */
export type JsonValidateOutput = { isValid: boolean; error: string | null; errorLine: number | null; errorColumn: number | null; errorContext: string | null; rootType: string | null; depth: number | null; keyCount: number | null; valueCount: number | null; arrayCount: number | null; objectCount: number | null; stringCount: number | null; numberCount: number | null; booleanCount: number | null; nullCount: number | null; maxArrayLength: number | null; hasDuplicateKeys: boolean; formatted: string | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * Signing algorithm for the JWT.
 */
export type JwtAlgorithm = "HS256" | "HS384" | "HS512" | "none"
/**
 * Input for JWT build.
 */
export type JwtBuildInput = { algorithm: JwtAlgorithm; secret: string; secretEncoding: SecretEncoding; 
/**
 * Raw JSON string for payload (empty treated as "{}").
 */
payloadJson: string; includeIat: boolean; includeExp: boolean; 
/**
 * Seconds from now for exp when include_exp is true.
 */
expSeconds: number; 
/**
 * Optional extra header claims as JSON, e.g. {"kid": "my-key-id"}.
 */
extraHeaders: string }
/**
 * Output of JWT build.
 */
export type JwtBuildOutput = { token: string; headerJson: string; payloadJson: string; headerB64: string; payloadB64: string; signatureB64: string; algorithm: string; expiresAt: string | null; issuedAt: string | null; error: string | null }
/**
 * Input for JWT decode.
 */
export type JwtDecodeInput = { 
/**
 * The JWT token string (header.payload.signature).
 */
token: string; 
/**
 * Optional secret for HMAC verification; empty string if not provided.
 */
secret: string; 
/**
 * How the secret is encoded when provided.
 */
secretEncoding: SecretEncoding }
/**
 * Output of JWT decode.
 */
export type JwtDecodeOutput = { 
/**
 * Base64url-decoded header JSON.
 */
headerRaw: string; 
/**
 * Base64url-decoded payload JSON.
 */
payloadRaw: string; 
/**
 * Signature bytes as hex.
 */
signatureRaw: string; algorithm: string; tokenType: string; keyId: string | null; subject: string | null; issuer: string | null; audience: string | null; issuedAt: number | null; expiresAt: number | null; notBefore: string | null; jwtId: string | null; issuedAtHuman: string | null; expiresAtHuman: string | null; isExpired: boolean | null; timeUntilExpiry: string | null; 
/**
 * exp - iat when both present.
 */
lifetimeSeconds: number | null; 
/**
 * Human-readable lifetime, e.g. "28 days", "2 hours".
 */
lifetimeHuman: string | null; 
/**
 * (now - iat) / (exp - iat) * 100, clamped 0.0–100.0.
 */
consumedPercent: number | null; 
/**
 * true if current time >= nbf; None if nbf not in token.
 */
nbfActive: boolean | null; 
/**
 * Full payload claims as pretty JSON.
 */
allClaims: string; signatureValid: boolean | null; signatureNote: string; partCount: number; isWellFormed: boolean; error: string | null }
export type LineOperation = "sortAsc" | "sortDesc" | "sortNaturalAsc" | "sortNaturalDesc" | "deduplicate" | "reverse" | "trimWhitespace" | "removeEmpty"
export type LineToolsInput = { text: string; 
/**
 * Ordered list of operations applied left-to-right.
 */
operations: LineOperation[]; 
/**
 * For Deduplicate: keep first occurrence (true) or last (false).
 */
keepFirst?: boolean; 
/**
 * For Sort/Deduplicate: case-insensitive comparison.
 */
caseInsensitive?: boolean }
export type LineToolsOutput = { result: string; inputLineCount: number; outputLineCount: number; changedCount: number; 
/**
 * Line ending style detected in input: "lf" | "crlf"
 */
lineEnding: string }
/**
 * Input for the Lorem Ipsum generator.
 */
export type LoremIpsumInput = { outputType: LoremOutputType; count: number; startWithClassic: boolean }
/**
 * Output: generated text and actual word/sentence/paragraph counts.
 */
export type LoremIpsumOutput = { result: string; wordCount: number; paragraphCount: number; sentenceCount: number; error: string | null }
/**
 * Output format: paragraphs, sentences, or words.
 */
export type LoremOutputType = "paragraphs" | "sentences" | "words"
export type MatchResult = { start: number; end: number; value: string; groups: (string | null)[] }
/**
 * Input for Nano ID generation.
 */
export type NanoIdInput = { 
/**
 * Number of IDs to generate (1–100).
 */
count: number; 
/**
 * Length of each ID (4–256). Default: 21.
 */
size: number; 
/**
 * Optional custom alphabet. If None or empty, uses the default URL-safe alphabet.
 */
alphabet: string | null }
/**
 * Output from Nano ID generation.
 */
export type NanoIdOutput = { 
/**
 * Generated IDs.
 */
ids: string[]; 
/**
 * Optional error message.
 */
error: string | null }
export type NatoPhoneticInput = { text: string; mode: NatoPhoneticMode }
export type NatoPhoneticMode = "encode" | "decode"
export type NatoPhoneticOutput = { result: string; error: string | null }
/**
 * Input base for the number string.
 */
export type NumberBase = "decimal" | "hexadecimal" | "binary" | "octal" | "base32" | "base36"
/**
 * Input for the Passphrase Generator tool.
 */
export type PassphraseInput = { 
/**
 * Number of words per passphrase. Clamped to 3–12.
 */
wordCount: number; 
/**
 * Number of passphrases to generate. Clamped to 1–20.
 */
count: number; separator: PassphraseSeparator; 
/**
 * Capitalise the first letter of each word.
 */
capitalize: boolean; 
/**
 * Append a random digit (0–9) at the end.
 */
includeNumber: boolean; 
/**
 * Append a random symbol from `!@#$%&*?` at the end.
 */
includeSymbol: boolean }
/**
 * Output from the Passphrase Generator tool.
 */
export type PassphraseOutput = { passphrases: string[]; 
/**
 * Shannon entropy in bits (log2(wordlist) * words, + extras).
 */
entropyBits: number; wordCount: number; wordlistSize: number; error: string | null }
/**
 * Word separator style.
 */
export type PassphraseSeparator = "Hyphen" | "Space" | "Dot" | "Underscore" | "None"
/**
 * Input for the Password Generator tool.
 */
export type PasswordInput = { 
/**
 * Password length. Clamped to 4–256.
 */
length: number; 
/**
 * Number of passwords to generate. Clamped to 1–50.
 */
count: number; includeUppercase: boolean; includeLowercase: boolean; includeNumbers: boolean; includeSymbols: boolean; 
/**
 * When true, removes visually ambiguous chars: 0, O, o, 1, I, l.
 */
excludeAmbiguous: boolean; 
/**
 * Symbol set to use when include_symbols is true.
 * Defaults to "!@#$%^&*()-_=+[]{}|;:,.<>?" if empty.
 */
symbols: string }
/**
 * Output from the Password Generator tool.
 */
export type PasswordOutput = { passwords: string[]; strength: PasswordStrength; 
/**
 * Shannon entropy: length × log₂(alphabet_size). 0.0 when alphabet is empty.
 */
entropyBits: number; 
/**
 * Size of the effective alphabet used for generation.
 */
alphabetSize: number; error: string | null }
/**
 * Strength tier based on Shannon entropy of the generated password.
 */
export type PasswordStrength = "Weak" | "Fair" | "Strong" | "VeryStrong"
/**
 * Human-readable permissions for one class (owner / group / others).
 */
export type PermissionClass = { read: boolean; write: boolean; execute: boolean; label: string }
export type QrCodeInput = { text: string; ecLevel?: QrEcLevel; 
/**
 * Size of each module in the SVG.
 */
moduleSize?: number; 
/**
 * Foreground colour as CSS hex string.
 */
fgColor?: string; 
/**
 * Background colour as CSS hex string.
 */
bgColor?: string; 
/**
 * Quiet zone size in modules.
 */
margin?: number }
export type QrCodeOutput = { 
/**
 * Complete SVG string, ready to embed or display.
 */
svg: string; 
/**
 * Side length of the QR code in modules (excluding quiet zone).
 */
size: number; 
/**
 * QR version number (1-40).
 */
qrVersion: number; 
/**
 * Approximate max byte capacity for current version + EC level.
 */
maxBytes: number; 
/**
 * Input length in UTF-8 bytes.
 */
inputBytes: number; error: string | null }
export type QrEcLevel = "low" | "medium" | "quartile" | "high"
/**
 * One query string key-value pair (decoded for display).
 */
export type QueryParam = { key: string; value: string }
export type RegexRequest = { pattern: string; text: string; engine: string; flags: string | null }
export type ResizeOptions = { width: number | null; height: number | null; maintainAspect: boolean }
/**
 * Which JSON Schema draft to use for validation.
 */
export type SchemaDraft = "draft7" | "2019-09" | "2020-12"
/**
 * How the verification secret is encoded.
 */
export type SecretEncoding = "utf8" | "base64" | "hex"
/**
 * How the primary version relates to `compare_with`.
 */
export type SemverCompareResult = "lessThan" | "equal" | "greaterThan"
/**
 * Input for the Semver tool.
 */
export type SemverInput = { 
/**
 * Version string (optional leading `v` is stripped).
 */
version: string; 
/**
 * Optional second version to compare (`Ordering` in `compare_result`).
 */
compareWith: string | null; 
/**
 * Optional requirement string (e.g. `^1.0.0`, `>=1.2.3 <2.0.0`).
 */
range: string | null }
/**
 * Output from Semver processing.
 */
export type SemverOutput = { major: number | null; minor: number | null; patch: number | null; prerelease: string; buildMetadata: string; 
/**
 * Normalized semver string for the parsed version.
 */
canonical: string; compareResult: SemverCompareResult | null; compareError: string | null; rangeSatisfied: boolean | null; rangeError: string | null; bumpedMajor: string | null; bumpedMinor: string | null; bumpedPatch: string | null; error: string | null }
/**
 * Input for the Slug Generator tool.
 */
export type SlugInput = { text: string; separator: string; lowercase: boolean; maxLength: number | null }
/**
 * Output of slug generation.
 */
export type SlugOutput = { slug: string; error: string | null }
export type SqlFormatInput = { 
/**
 * Raw SQL string to format.
 */
value: string; 
/**
 * Indentation style.
 */
indent: SqlIndentStyle; 
/**
 * Keyword casing style.
 */
keywordCase: SqlKeywordCase }
export type SqlFormatOutput = { result: string; lineCount: number; charCount: number; 
/**
 * Human-readable error if formatting failed (rare with sqlformat).
 */
error: string | null }
export type SqlIndentStyle = "spaces2" | "spaces4" | "tab"
export type SqlKeywordCase = "upper" | "lower" | "preserve"
/**
 * Input for the String Escaper tool.
 */
export type StringEscaperInput = { text: string; mode: EscapeMode; target: EscapeTarget }
/**
 * Output: result string, number of replacements, optional error.
 */
export type StringEscaperOutput = { result: string; changes: number; error: string | null }
export type SubnetSplit = { subPrefix: number; count: number; examples: string[] }
export type TextDiffAnnotatedLine = { lineNumber: number; content: string; annotation: TextDiffLineAnnotation; 
/**
 * Inline spans for word/char granularity on changed lines.
 * Empty for unchanged lines or when granularity is Line.
 */
spans: TextDiffSpan[]; 
/**
 * true when char granularity fell back to full-line highlight.
 */
fellBack: boolean }
export type TextDiffInput = { left: string; right: string; 
/**
 * Defaults to Word if omitted.
 */
granularity?: DiffGranularity }
export type TextDiffLineAnnotation = "unchanged" | "added" | "removed"
export type TextDiffOutput = { isIdentical: boolean; addedCount: number; removedCount: number; unchangedCount: number; leftAnnotated: TextDiffAnnotatedLine[]; rightAnnotated: TextDiffAnnotatedLine[]; 
/**
 * true if any line fell back from char granularity to full-line highlight.
 */
hasFallback: boolean }
export type TextDiffSpan = { text: string; 
/**
 * true = this segment is different (highlight it); false = unchanged
 */
highlighted: boolean }
/**
 * Input for the timestamp converter.
 */
export type TimestampInput = { 
/**
 * The timestamp or date string to convert (ignored when mode is Now).
 */
value: string; mode: TimestampMode; 
/**
 * Only used when mode is ToHuman: treat value as seconds or milliseconds.
 */
unit: TimestampUnit }
/**
 * Conversion direction or "current time".
 */
export type TimestampMode = 
/**
 * Unix timestamp → human-readable formats.
 */
"toHuman" | 
/**
 * Date string → Unix timestamp.
 */
"toUnix" | 
/**
 * Use current time; value is ignored.
 */
"now"
/**
 * Output: all formats for the resolved instant.
 */
export type TimestampOutput = { unixSeconds: number; unixMilliseconds: number; 
/**
 * e.g. 2024-03-04T12:00:00Z
 */
iso8601: string; 
/**
 * e.g. Mon, 04 Mar 2024 12:00:00 +0000
 */
rfc2822: string; 
/**
 * e.g. 2024-03-04 12:00:00 UTC
 */
utcHuman: string; 
/**
 * e.g. 2024-03-04
 */
dateOnly: string; 
/**
 * e.g. 12:00:00
 */
timeOnly: string; 
/**
 * e.g. Monday
 */
dayOfWeek: string; 
/**
 * e.g. "2 days ago", "in 3 hours", "just now"
 */
relative: string; isFuture: boolean; error: string | null }
/**
 * Unit for ToHuman mode.
 */
export type TimestampUnit = "seconds" | "milliseconds"
/**
 * Input for the timezone converter.
 */
export type TimezoneInput = { 
/**
 * Date/time string to convert (interpreted in from_tz).
 */
datetime: string; 
/**
 * IANA timezone for the input, e.g. "America/New_York".
 */
fromTz: string; 
/**
 * IANA timezone for the output, e.g. "Europe/London".
 */
toTz: string }
/**
 * Output of the timezone conversion.
 */
export type TimezoneOutput = { 
/**
 * Converted datetime, e.g. "2024-03-04 07:00:00".
 */
result: string; 
/**
 * ISO 8601 with offset, e.g. "2024-03-04T07:00:00-05:00".
 */
resultIso: string; fromOffset: string; toOffset: string; fromAbbr: string; toAbbr: string; fromDst: boolean; toDst: boolean; 
/**
 * e.g. "+5 hours", "-5 hours", "+5:30 hours", "0 hours (same zone)".
 */
difference: string; error: string | null }
export type TotpAlgorithm = "sha1" | "sha256" | "sha512"
export type TotpInput = { 
/**
 * Base32-encoded TOTP secret (spaces are stripped before parsing).
 */
secret: string; 
/**
 * HMAC algorithm. Default: Sha1.
 */
algorithm: TotpAlgorithm; 
/**
 * Number of digits in the output code (6 or 8). Default: 6.
 */
digits: number; 
/**
 * Time step in seconds (30 or 60). Default: 30.
 */
period: number; 
/**
 * Current Unix timestamp in seconds (supplied by the caller — do not use
 * system time here so WASM works without clock access).
 */
timestamp: number }
export type TotpOutput = { 
/**
 * The current OTP code (zero-padded to `digits` length).
 */
code: string; 
/**
 * The next OTP code (one period ahead — useful for testing).
 */
nextCode: string; 
/**
 * Seconds remaining in the current time window.
 */
validFor: number; 
/**
 * Progress through the current window as a value 0.0–1.0 (1.0 = just
 * started rolling toward expiry, 0.0 = about to expire). Use for the countdown bar.
 */
progress: number; 
/**
 * Error message if the secret is invalid or generation failed.
 */
error: string | null }
/**
 * A single tool entry for the tray menu — id and display name from the frontend.
 */
export type TrayToolItem = { id: string; name: string }
export type UaParseInput = { ua: string }
export type UaParseOutput = { 
/**
 * Browser name, e.g. "Chrome", "Firefox", "Safari".
 */
browserName: string | null; 
/**
 * Browser version string, e.g. "120.0.0.0".
 */
browserVersion: string | null; 
/**
 * Operating system name, e.g. "Mac OSX", "Windows", "iOS".
 */
os: string | null; 
/**
 * OS version string if available.
 */
osVersion: string | null; 
/**
 * High-level device classification: "Desktop", "Mobile", "Tablet", "Bot", "Other", "Unknown".
 */
deviceType: string; 
/**
 * Rendering engine: "Blink", "Gecko", "WebKit", "Trident", "EdgeHTML", or "Presto".
 */
engine: string | null; 
/**
 * True when the UA belongs to a crawler, bot, or spider.
 */
isBot: boolean; 
/**
 * Hardware vendor if detectable (e.g. "Apple", "Samsung").
 */
vendor: string | null; 
/**
 * Raw woothee category string for reference ("pc", "smartphone", "crawler", etc.).
 */
category: string; error: string | null }
/**
 * Input for the ULID Generator tool.
 */
export type UlidInput = { 
/**
 * Number of ULIDs to generate (1–100).
 */
count: number; 
/**
 * If true, return ULIDs in uppercase (default ULID form); otherwise lowercase.
 */
uppercase: boolean }
/**
 * Input for ULID inspection.
 */
export type UlidInspectInput = { 
/**
 * Raw ULID string (26 chars, Crockford Base32).
 */
value: string }
/**
 * Output from ULID inspection.
 */
export type UlidInspectOutput = { isValid: boolean; timestampMs: number | null; timestampHuman: string | null; timestampIso: string | null; randomness: string | null; asUppercase: string | null; asLowercase: string | null; error: string | null }
/**
 * Output from the ULID Generator tool.
 */
export type UlidOutput = { 
/**
 * Generated ULIDs as 26-character Base32 strings.
 */
ulids: string[]; 
/**
 * Optional error message when generation fails (e.g. invalid count).
 */
error: string | null }
/**
 * One inspected character row.
 */
export type UnicodeChar = { char: string; codepoint: number; hex: string; name: string; block: string; category: string; utf8Bytes: number[]; utf8Hex: string }
/**
 * Input for the Unicode Inspector tool.
 */
export type UnicodeInspectInput = { text: string }
/**
 * Output of Unicode inspection.
 */
export type UnicodeInspectOutput = { chars: UnicodeChar[]; totalChars: number; totalBytes: number; error: string | null }
export type UnitCategory = "dataSize" | "time" | "temperature" | "length" | "weight" | "speed" | "angle" | "frequency"
export type UnitConverterInput = { value: number; 
/**
 * Short unit key, e.g. "km", "mb", "fahrenheit". See unit tables below.
 */
fromUnit: string; category: UnitCategory }
export type UnitConverterOutput = { results: UnitResult[]; error: string | null }
export type UnitResult = { 
/**
 * Short key, e.g. "km"
 */
unit: string; 
/**
 * Display label, e.g. "Kilometre (km)"
 */
label: string; 
/**
 * Numeric result
 */
value: number; 
/**
 * Pre-formatted string with appropriate precision
 */
formatted: string }
/**
 * Input for the URL encode/decode tool.
 */
export type UrlEncodeInput = { text: string; mode: UrlEncodeMode; encodeType: UrlEncodeType }
/**
 * Whether to encode or decode.
 */
export type UrlEncodeMode = "encode" | "decode"
/**
 * Output: result string and optional error message.
 */
export type UrlEncodeOutput = { result: string; error: string | null }
/**
 * Full: encodes everything including / ? & =.
 * Component: encodes only special chars, preserves / (e.g. for path segments).
 */
export type UrlEncodeType = "full" | "component"
/**
 * Input for the URL parse tool.
 */
export type UrlParseInput = { value: string }
/**
 * Output from the URL parser.
 */
export type UrlParseOutput = { scheme: string | null; username: string | null; password: string | null; host: string | null; port: number | null; path: string | null; 
/**
 * Raw query string (as in the URL, not decoded).
 */
query: string | null; 
/**
 * Parsed key/value pairs (decoded).
 */
params: QueryParam[]; fragment: string | null; 
/**
 * scheme + host + port when origin is a tuple (opaque origins yield None).
 */
origin: string | null; error: string | null }
/**
 * Input for the UUID Generator tool.
 */
export type UuidInput = { 
/**
 * UUID version to generate (V4 random, V7 time-ordered).
 */
version: UuidVersion; 
/**
 * Number of UUIDs to generate (1–100).
 */
count: number; 
/**
 * If true, return UUIDs in uppercase; otherwise lowercase.
 */
uppercase: boolean }
/**
 * Input for UUID inspection.
 */
export type UuidInspectInput = { 
/**
 * Raw UUID string (with or without braces/URN prefix).
 */
value: string }
/**
 * Output from UUID inspection.
 */
export type UuidInspectOutput = { isValid: boolean; version: number | null; versionName: string | null; variant: string | null; v1Timestamp: string | null; v1ClockSeq: number | null; v1Node: string | null; v7Timestamp: string | null; asUppercase: string | null; asLowercase: string | null; asUrn: string | null; asBraces: string | null; asRawBytes: string | null; error: string | null }
/**
 * Output from the UUID Generator tool.
 */
export type UuidOutput = { 
/**
 * Generated UUIDs in canonical text form.
 */
uuids: string[]; 
/**
 * Optional error message when generation fails (e.g. invalid count).
 */
error: string | null }
/**
 * Which UUID version to generate.
 */
export type UuidVersion = "v1" | "v4" | "v7"
/**
 * A single validation issue (one schema violation).
 */
export type ValidationIssue = { 
/**
 * JSON Pointer path to the failing instance node (e.g. "/user/age").
 */
instancePath: string; 
/**
 * Human-readable error message.
 */
message: string; 
/**
 * JSON Pointer path into the schema that produced the error.
 */
schemaPath: string }
/**
 * Input for the Word Counter tool.
 */
export type WordCounterInput = { text: string }
/**
 * Output for the Word Counter tool: all stats in one struct.
 */
export type WordCounterOutput = { words: number; charactersWithSpaces: number; charactersWithoutSpaces: number; lines: number; sentences: number; paragraphs: number; uniqueWords: number; avgWordLength: number; readingTimeSeconds: number; error: string | null }
export type XmlFormatInput = { 
/**
 * Raw XML text to format.
 */
value: string; 
/**
 * Indentation size in spaces (2 or 4). Defaults to 2.
 */
indentSize: number }
export type XmlFormatOutput = { 
/**
 * Formatted XML string.
 */
result: string; 
/**
 * Number of lines in formatted output.
 */
lineCount: number; 
/**
 * Character count of formatted output.
 */
charCount: number; 
/**
 * Error message if parsing/formatting failed.
 */
error: string | null }
export type YamlFormatInput = { 
/**
 * Raw YAML text to format.
 */
value: string }
export type YamlFormatOutput = { 
/**
 * Normalised YAML string.
 */
result: string; 
/**
 * Number of lines in formatted output.
 */
lineCount: number; 
/**
 * Character count.
 */
charCount: number; 
/**
 * Error message if parsing failed.
 */
error: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
