// Generated by tauri-specta on `pnpm tauri dev` (debug builds only).
// This committed stub lets the web/CI build resolve the import without the real file.
// Do not edit — it is overwritten each desktop dev session.
export const commands: Record<string, (input: unknown) => Promise<unknown>> = {};
