// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InlineSpan = { text: string, 
/**
 * true = this segment is different (highlight it); false = unchanged
 */
highlighted: boolean, };
