// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffGranularity } from "./DiffGranularity";

export type TextDiffInput = { left: string, right: string, 
/**
 * Defaults to Word if omitted.
 */
granularity: DiffGranularity, };
