// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnnotatedLine } from "./TextDiffAnnotatedLine";

export type TextDiffOutput = { isIdentical: boolean, addedCount: number, removedCount: number, unchangedCount: number, leftAnnotated: Array<AnnotatedLine>, rightAnnotated: Array<AnnotatedLine>, 
/**
 * true if any line fell back from char granularity to full-line highlight.
 */
hasFallback: boolean, };
