// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for the timezone converter.
 */
export type TimezoneInput = { 
/**
 * Date/time string to convert (interpreted in from_tz).
 */
datetime: string, 
/**
 * IANA timezone for the input, e.g. "America/New_York".
 */
fromTz: string, 
/**
 * IANA timezone for the output, e.g. "Europe/London".
 */
toTz: string, };
