// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unit for ToHuman mode.
 */
export type TimestampUnit = "seconds" | "milliseconds";
