// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TotpAlgorithm } from "./TotpAlgorithm";

export type TotpInput = { 
/**
 * Base32-encoded TOTP secret (spaces are stripped before parsing).
 */
secret: string, 
/**
 * HMAC algorithm. Default: Sha1.
 */
algorithm: TotpAlgorithm, 
/**
 * Number of digits in the output code (6 or 8). Default: 6.
 */
digits: number, 
/**
 * Time step in seconds (30 or 60). Default: 30.
 */
period: number, 
/**
 * Current Unix timestamp in seconds (supplied by the caller — do not use
 * system time here so WASM works without clock access).
 */
timestamp: number, };
