// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TotpOutput = { 
/**
 * The current OTP code (zero-padded to `digits` length).
 */
code: string, 
/**
 * The next OTP code (one period ahead — useful for testing).
 */
nextCode: string, 
/**
 * Seconds remaining in the current time window.
 */
validFor: number, 
/**
 * Progress through the current window as a value 0.0–1.0 (1.0 = just
 * started rolling toward expiry, 0.0 = about to expire). Use for the countdown bar.
 */
progress: number, 
/**
 * Error message if the secret is invalid or generation failed.
 */
error: string | null, };
