// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output from ULID inspection.
 */
export type UlidInspectOutput = { isValid: boolean, timestampMs: bigint | null, timestampHuman: string | null, timestampIso: string | null, randomness: string | null, asUppercase: string | null, asLowercase: string | null, error: string | null, };
