// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for ULID inspection.
 */
export type UlidInspectInput = { 
/**
 * Raw ULID string (26 chars, Crockford Base32).
 */
value: string, };
