// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for the ULID Generator tool.
 */
export type UlidInput = { 
/**
 * Number of ULIDs to generate (1–100).
 */
count: number, 
/**
 * If true, return ULIDs in uppercase (default ULID form); otherwise lowercase.
 */
uppercase: boolean, };
