// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnicodeChar } from "./UnicodeChar";

/**
 * Output of Unicode inspection.
 */
export type UnicodeInspectOutput = { chars: Array<UnicodeChar>, totalChars: number, totalBytes: number, error: string | null, };
