// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnitResult } from "./UnitResult";

export type UnitConverterOutput = { results: Array<UnitResult>, error: string | null, };
