// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UnitResult = { 
/**
 * Short key, e.g. "km"
 */
unit: string, 
/**
 * Display label, e.g. "Kilometre (km)"
 */
label: string, 
/**
 * Numeric result
 */
value: number, 
/**
 * Pre-formatted string with appropriate precision
 */
formatted: string, };
