// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output: result string and optional error message.
 */
export type UrlEncodeOutput = { result: string, error: string | null, };
