// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Full: encodes everything including / ? & =.
 * Component: encodes only special chars, preserves / (e.g. for path segments).
 */
export type UrlEncodeType = "full" | "component";
