// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for UUID inspection.
 */
export type UuidInspectInput = { 
/**
 * Raw UUID string (with or without braces/URN prefix).
 */
value: string, };
