// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output from UUID inspection.
 */
export type UuidInspectOutput = { isValid: boolean, version: number | null, versionName: string | null, variant: string | null, v1Timestamp: string | null, v1ClockSeq: number | null, v1Node: string | null, v7Timestamp: string | null, asUppercase: string | null, asLowercase: string | null, asUrn: string | null, asBraces: string | null, asRawBytes: string | null, error: string | null, };
