// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output from the UUID Generator tool.
 */
export type UuidOutput = { 
/**
 * Generated UUIDs in canonical text form.
 */
uuids: Array<string>, 
/**
 * Optional error message when generation fails (e.g. invalid count).
 */
error: string | null, };
