// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output for the Word Counter tool: all stats in one struct.
 */
export type WordCounterOutput = { words: number, charactersWithSpaces: number, charactersWithoutSpaces: number, lines: number, sentences: number, paragraphs: number, uniqueWords: number, avgWordLength: number, readingTimeSeconds: number, error: string | null, };
