// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type YamlFormatOutput = { 
/**
 * Normalised YAML string.
 */
result: string, 
/**
 * Number of lines in formatted output.
 */
lineCount: number, 
/**
 * Character count.
 */
charCount: number, 
/**
 * Error message if parsing failed.
 */
error: string | null, };
